//! Gated `DeltaNet` (GDN) primitives for the `qwen3_5` family — grad-bearing.
//!
//! candle ships no `qwen3_5`/`qwen3_next` and no gated-delta-rule kernel, so the
//! linear-attention primitive is ours. Everything here is a **line-faithful port
//! of the transformers v5 reference fallbacks** in
//! `models/qwen3_5/modeling_qwen3_5.py` (the exact code production transformers
//! executes on CPU), pinned against committed fixtures dumped from that very
//! code (`tests/fixtures/gdn_golden.json`, generated by
//! `scripts/oracle/gen_gdn_golden.py` in the pinned `ferrl-oracle` env):
//!
//! - [`gated_delta_rule_chunked`] ← `torch_chunk_gated_delta_rule` — the
//!   chunked WY-form scan (chunk 64). **This is the training/prefill kernel**:
//!   autograd memory scales per *chunk*, not per token (the sequential form
//!   retains ~3 state-sized tensors per token per layer — hopeless at training
//!   shapes).
//! - [`gated_delta_rule_recurrent`] ← `torch_recurrent_gated_delta_rule` — the
//!   exact sequential recurrence. **This is the single-token decode kernel**
//!   and the cross-check oracle for the chunked form (same math, different
//!   schedule; they agree to float roundoff).
//! - [`causal_depthwise_conv1d`] — the pre-kernel causal conv, implemented as
//!   K shifted-tap broadcasts (the `mamba2.rs` pattern) instead of
//!   `Tensor::conv1d(groups = C)`: candle's grouped conv decomposes into C
//!   per-channel convs + cat (differentiable but pathologically slow at
//!   `conv_dim` ≈ thousands).
//! - [`l2norm`] / [`stable_softplus`] — the FLA-convention q/k normalizer
//!   (eps inside the rsqrt, on the **sum** of squares) and an overflow-safe
//!   softplus (candle has none; the naive `ln(exp(x)+1)` overflows and NaNs
//!   the backward).
//!
//! Numerics contract (mirrors the reference exactly): all kernel inputs are
//! upcast to F32 at entry, the recurrent state lives in **F32** for the whole
//! sequence, and only the output is cast back to the input dtype. The decay
//! `g` must be computed in F32 upstream (`-exp(A_log) * softplus(a + dt_bias)`
//! — in fp16/bf16 the `exp(A_log)` path can produce `-inf`).
//!
//! Everything is built from ops with verified candle backward (no fused
//! no-backward kernels), so both kernels are safe in the tape-bearing grad
//! forward; the planted-bug negative controls in the tests keep the fixture
//! gates non-vacuous.

use candle_core::{bail, DType, Result as CandleResult, Tensor, D};

/// Overflow-safe softplus: `relu(x) + ln(1 + exp(-|x|))`.
///
/// Equals `ln(1 + exp(x))` everywhere, but never exponentiates a positive
/// value, so large `x` cannot overflow forward or NaN the backward (the naive
/// composite does both). All component ops have candle backward.
///
/// # Errors
///
/// Returns a candle error if an underlying tensor op fails.
pub fn stable_softplus(x: &Tensor) -> CandleResult<Tensor> {
    let lin = x.relu()?;
    let log_term = (x.abs()?.neg()?.exp()? + 1.0)?.log()?;
    lin + log_term
}

/// L2-normalize `x` over its last dimension, FLA-convention:
/// `x * rsqrt(sum(x^2) + eps)`.
///
/// The eps sits **inside** the rsqrt, added to the **sum** of squares (not the
/// mean, not the norm) — exactly the `l2norm` of the transformers `qwen3_5`
/// reference ("intended to align with the l2norm implementation in the FLA
/// library"). A `x / (norm + eps)` form diverges from the oracle at the ~1e-3
/// scale on unit-norm-ish vectors.
///
/// # Errors
///
/// Returns a candle error if an underlying tensor op fails.
pub fn l2norm(x: &Tensor, eps: f64) -> CandleResult<Tensor> {
    let ss = (x.sqr()?.sum_keepdim(D::Minus1)? + eps)?;
    x.broadcast_div(&ss.sqrt()?)
}

/// Causal depthwise conv1d over the sequence dim, as K shifted-tap broadcasts.
///
/// `x` is `[batch, channels, len]`, `weight` is `[channels, kernel]` (the
/// checkpoint's `conv1d.weight [C, 1, K]` with the singleton squeezed), and
/// `left_context` — when present — is the last `kernel - 1` *inputs* preceding
/// `x` (shape `[batch, channels, kernel - 1]`); when absent the left context
/// is zero (the prefill-at-position-0 case). Output is `[batch, channels,
/// len]`: position `t` sees inputs `t - kernel + 1 ..= t`, i.e. exactly
/// `F.conv1d(pad_left(x, kernel - 1), weight, groups = channels)` truncated to
/// `len` — the transformers reference conv (bias-free; the caller applies the
/// `SiLU`).
///
/// Implementation note: the depthwise conv is computed as
/// `sum_k weight[:, k] * shift_k(x)` over `kernel` narrowed views of the
/// padded input (the candle `mamba2.rs` pattern). `Tensor::conv1d(groups=C)`
/// would be correct and differentiable but decomposes into `C` single-channel
/// convs + a `C`-way cat per call — pathological at GDN widths.
///
/// CACHING CONTRACT (the decode-path trap, pinned by the handoff gate): the
/// state a cached decoder must carry forward is the last `kernel - 1` columns
/// of the **pre-activation conv input** (what this function consumes as
/// `left_context`), never the conv *output* and never post-SiLU values.
///
/// # Errors
///
/// Returns a candle error if `x`/`weight`/`left_context` ranks or dims are
/// inconsistent, or an underlying tensor op fails.
pub fn causal_depthwise_conv1d(
    x: &Tensor,
    weight: &Tensor,
    left_context: Option<&Tensor>,
) -> CandleResult<Tensor> {
    let (b, c, l) = x.dims3()?;
    let (wc, kernel) = weight.dims2()?;
    if wc != c {
        bail!("causal_depthwise_conv1d: weight has {wc} channels, input has {c}");
    }
    if kernel == 0 {
        bail!("causal_depthwise_conv1d: kernel must be >= 1");
    }
    let padded = match left_context {
        Some(ctx) => {
            let (cb, cc, cl) = ctx.dims3()?;
            if (cb, cc, cl) != (b, c, kernel - 1) {
                bail!(
                    "causal_depthwise_conv1d: left_context is [{cb}, {cc}, {cl}], \
                     expected [{b}, {c}, {}]",
                    kernel - 1
                );
            }
            Tensor::cat(&[ctx, x], D::Minus1)?
        }
        None => x.pad_with_zeros(D::Minus1, kernel - 1, 0)?,
    };
    // y[t] = sum_k w[:, k] * padded[t + k]  (k = 0 is the oldest tap).
    let mut acc: Option<Tensor> = None;
    for k in 0..kernel {
        let tap = padded.narrow(D::Minus1, k, l)?;
        let w_k = weight.narrow(1, k, 1)?.reshape((1, c, 1))?;
        let term = tap.broadcast_mul(&w_k)?;
        acc = Some(match acc {
            Some(a) => (a + term)?,
            None => term,
        });
    }
    // kernel >= 1, so acc is always Some.
    acc.ok_or_else(|| candle_core::Error::Msg("unreachable: empty kernel".into()))
}

/// Validated, F32-upcast kernel inputs shared by both delta-rule forms.
struct GdnInputs {
    /// `[batch, heads, seq, k_dim]`, l2-normalized and pre-scaled by
    /// `1/sqrt(k_dim)`, F32.
    query: Tensor,
    /// `[batch, heads, seq, k_dim]`, l2-normalized, F32.
    key: Tensor,
    /// `[batch, heads, seq, v_dim]`, F32.
    value: Tensor,
    /// `[batch, heads, seq]` log-space decay (`<= 0`), F32.
    g: Tensor,
    /// `[batch, heads, seq]` write strength in `(0, 1)`, F32.
    beta: Tensor,
    /// `[batch, heads, k_dim, v_dim]` initial state, F32 (zeros if absent).
    state: Tensor,
    /// The dtype of the caller's `query`, to cast the output back to.
    out_dtype: DType,
}

/// Validate shapes, l2-normalize q/k, apply the `1/sqrt(K)` query scale,
/// transpose `[B, T, H, *] -> [B, H, T, *]`, upcast to F32, and resolve the
/// initial state — the shared entry of both kernels, mirroring the reference
/// preamble (`use_qk_l2norm_in_kernel=True` semantics).
fn prepare_inputs(
    query: &Tensor,
    key: &Tensor,
    value: &Tensor,
    g: &Tensor,
    beta: &Tensor,
    initial_state: Option<&Tensor>,
) -> CandleResult<GdnInputs> {
    let (b, t, h, k_dim) = query.dims4()?;
    let (kb, kt, kh, kk) = key.dims4()?;
    let (vb, vt, vh, v_dim) = value.dims4()?;
    if (kb, kt, kh, kk) != (b, t, h, k_dim) {
        bail!(
            "gdn: key dims {:?} != query dims {:?}",
            key.dims(),
            query.dims()
        );
    }
    if (vb, vt, vh) != (b, t, h) {
        bail!(
            "gdn: value dims {:?} incompatible with query {:?}",
            value.dims(),
            query.dims()
        );
    }
    for (name, x) in [("g", g), ("beta", beta)] {
        let (gb, gt, gh) = x.dims3()?;
        if (gb, gt, gh) != (b, t, h) {
            bail!("gdn: {name} dims {:?}, expected [{b}, {t}, {h}]", x.dims());
        }
    }
    let out_dtype = query.dtype();

    // Contract guard (debug builds only — a device sync per call): g is
    // log-space decay and must be <= 0; a positive g overflows exp() in the
    // chunked decay masks. The model layer constructs
    // g = -exp(A_log) * softplus(..) which is <= 0 by construction.
    #[cfg(debug_assertions)]
    {
        let g_max = g
            .flatten_all()?
            .max(0)?
            .to_dtype(DType::F32)?
            .to_scalar::<f32>()?;
        if g_max > 0.0 {
            bail!("gdn: g must be log-space decay (<= 0), got max {g_max}");
        }
    }

    // l2norm BEFORE the transpose, exactly as the reference.
    let query = l2norm(query, 1e-6)?;
    let key = l2norm(key, 1e-6)?;

    let to_f32 = |x: &Tensor| -> CandleResult<Tensor> {
        x.transpose(1, 2)?.contiguous()?.to_dtype(DType::F32)
    };
    let scale = 1.0 / (k_dim as f64).sqrt();
    let query = (to_f32(&query)? * scale)?;
    let key = to_f32(&key)?;
    let value = to_f32(value)?;
    let g = g.transpose(1, 2)?.contiguous()?.to_dtype(DType::F32)?;
    let beta = beta.transpose(1, 2)?.contiguous()?.to_dtype(DType::F32)?;

    let state = match initial_state {
        Some(s) => {
            let (sb, sh, sk, sv) = s.dims4()?;
            if (sb, sh, sk, sv) != (b, h, k_dim, v_dim) {
                bail!(
                    "gdn: initial_state dims {:?}, expected [{b}, {h}, {k_dim}, {v_dim}]",
                    s.dims()
                );
            }
            s.to_dtype(DType::F32)?
        }
        None => Tensor::zeros((b, h, k_dim, v_dim), DType::F32, query.device())?,
    };
    Ok(GdnInputs {
        query,
        key,
        value,
        g,
        beta,
        state,
        out_dtype,
    })
}

/// The gated delta rule as an **exact sequential recurrence** — the decode
/// kernel, and the cross-check oracle for [`gated_delta_rule_chunked`].
///
/// Per token (state `S` is `[k_dim, v_dim]` per batch/head, F32):
///
/// ```text
/// S   <- exp(g_t) * S                       (decay BEFORE the read)
/// d_t  = beta_t * (v_t - S^T k_t)
/// S   <- S + k_t (x) d_t
/// o_t  = S^T q_t
/// ```
///
/// with q/k l2-normalized and q pre-scaled by `1/sqrt(k_dim)` (done inside,
/// matching `use_qk_l2norm_in_kernel=True`).
///
/// Layouts (the transformers convention): `query`/`key` `[batch, seq, heads,
/// k_dim]`, `value` `[batch, seq, heads, v_dim]`, `g` (log-space decay, `<=
/// 0`, **computed in F32 upstream**) and `beta` (post-sigmoid) `[batch, seq,
/// heads]`; `initial_state` `[batch, heads, k_dim, v_dim]`. Any GVA
/// query/key-head broadcast happens at the caller. Returns `(output, state)`:
/// `output` `[batch, seq, heads, v_dim]` in the input dtype, `state` `[batch,
/// heads, k_dim, v_dim]` **F32**.
///
/// Cost: `O(seq)` sequential steps and — when on the tape — `O(seq)`
/// state-sized saved tensors. Use for single-token decode and short
/// cross-check gates; training/prefill belongs to
/// [`gated_delta_rule_chunked`].
///
/// # Errors
///
/// Returns a candle error on rank/shape mismatches (fail-loud) or if an
/// underlying tensor op fails.
pub fn gated_delta_rule_recurrent(
    query: &Tensor,
    key: &Tensor,
    value: &Tensor,
    g: &Tensor,
    beta: &Tensor,
    initial_state: Option<&Tensor>,
) -> CandleResult<(Tensor, Tensor)> {
    let inp = prepare_inputs(query, key, value, g, beta, initial_state)?;
    let (_b, _h, t, _k_dim) = inp.key.dims4()?;
    let mut state = inp.state;
    let mut outs: Vec<Tensor> = Vec::with_capacity(t);
    for i in 0..t {
        let q_t = inp.query.narrow(2, i, 1)?.squeeze(2)?; // [B, H, K]
        let k_t = inp.key.narrow(2, i, 1)?.squeeze(2)?;
        let v_t = inp.value.narrow(2, i, 1)?.squeeze(2)?; // [B, H, V]
        let g_t = inp.g.narrow(2, i, 1)?.exp()?.unsqueeze(D::Minus1)?; // [B, H, 1, 1]
        let beta_t = inp.beta.narrow(2, i, 1)?; // [B, H, 1]

        state = state.broadcast_mul(&g_t)?;
        let kv_mem = state.broadcast_mul(&k_t.unsqueeze(D::Minus1)?)?.sum(2)?; // [B, H, V]
        let delta = (v_t - kv_mem)?.broadcast_mul(&beta_t)?;
        state = state.broadcast_add(
            &k_t.unsqueeze(D::Minus1)?
                .broadcast_mul(&delta.unsqueeze(D::Minus2)?)?,
        )?;
        outs.push(state.broadcast_mul(&q_t.unsqueeze(D::Minus1)?)?.sum(2)?);
    }
    let out = Tensor::stack(&outs, 2)?; // [B, H, T, V]
    let out = out.transpose(1, 2)?.contiguous()?.to_dtype(inp.out_dtype)?;
    Ok((out, state))
}

/// Strictly-lower-triangular `[c, c]` F32 mask (`1` where `row > col`).
fn strict_lower_mask(c: usize, device: &candle_core::Device) -> CandleResult<Tensor> {
    let tril = Tensor::tril2(c, DType::F32, device)?;
    let eye = Tensor::eye(c, DType::F32, device)?;
    tril - eye
}

/// Batched matmul over arbitrary leading batch dims, by flattening to 3-D.
///
/// candle 0.10.2's matmul supports at most two contiguous batch dims (4-D);
/// the 5-D `[b, h, n, c, *]` chunked-path layouts fail its striding check
/// with `MatMulUnexpectedStriding` even when contiguous, so every
/// chunked-path matmul routes through this: flatten the batch dims, matmul
/// at 3-D, reshape back. Reshape/contiguous both carry gradient, so the tape
/// is unaffected.
fn bmm(a: &Tensor, b: &Tensor) -> CandleResult<Tensor> {
    let ad = a.dims();
    let bd = b.dims();
    if ad.len() < 2 || ad.len() != bd.len() || ad[..ad.len() - 2] != bd[..bd.len() - 2] {
        bail!("bmm: incompatible batch dims {ad:?} vs {bd:?}");
    }
    let (m, k) = (ad[ad.len() - 2], ad[ad.len() - 1]);
    let (k2, n) = (bd[bd.len() - 2], bd[bd.len() - 1]);
    if k != k2 {
        bail!("bmm: inner dims {k} vs {k2} ({ad:?} x {bd:?})");
    }
    let batch: usize = ad[..ad.len() - 2].iter().product();
    let a3 = a.contiguous()?.reshape((batch, m, k))?;
    let b3 = b.contiguous()?.reshape((batch, k2, n))?;
    let out_shape: Vec<usize> = ad[..ad.len() - 2].iter().copied().chain([m, n]).collect();
    a3.matmul(&b3)?.reshape(out_shape)
}

/// The within-chunk UT-transform inverse: `(I - A)^{-1}` for strictly-lower
/// `A` `[.., c, c]` — nilpotent binary doubling,
/// `(I - A)^{-1} = sum_{k<c} A^k = prod_j (I + A^{2^j})`, `O(log c)` matmuls.
///
/// ⚠ Forming the EXPLICIT inverse is not backward stable: when `(I - A)^{-1}`
/// has large entries (the weak-decay / strong-key-coupling regime real
/// checkpoints actually visit), the rounding error of the doubling products
/// grows with the inverse's own magnitude — and that magnitude grows with row
/// index, so late-chunk positions degrade most (measured on the real 0.8B: up
/// to 1.1e-2 logit divergence by position 22, vs a flat ~5e-5 for the stable
/// solver). Use this only for the SMALL diagonal blocks inside [`ut_solve`]
/// (growth over `UT_SOLVE_BLOCK` rows is bounded); never on a full chunk.
fn ut_inverse(attn: &Tensor, c: usize) -> CandleResult<Tensor> {
    let eye = Tensor::eye(c, attn.dtype(), attn.device())?;
    // result = sum_{k < span} A^k, starting at span = 2 (I + A).
    let mut result = attn.broadcast_add(&eye)?;
    let mut power = attn.clone();
    let mut span = 2usize;
    while span < c {
        power = bmm(&power, &power)?; // A^span
        result = (bmm(&result, &power)? + result)?; // result * (I + A^span)
        span *= 2;
    }
    // Any overshoot terms (span rounding past c) are A^{>=c} = 0 by
    // nilpotency, so the result is exact for every c >= 1.
    Ok(result)
}

/// Diagonal-block width for [`ut_solve`]. Small enough that the explicit
/// block inverse's error growth stays bounded (≤ 8 substitution steps' worth);
/// large enough that a 64-chunk solve is 8 block steps of dense matmuls, not
/// 64 row updates.
const UT_SOLVE_BLOCK: usize = 8;

/// Solve `(I - A) X = B` for strictly-lower `A` `[.., c, c]` and
/// `B` `[.., c, r]` — **block forward substitution**, the numerically stable
/// replacement for multiplying by the explicit [`ut_inverse`].
///
/// The transformers reference solves this row by row (backward-stable
/// substitution, but `c` sequential row updates whose autograd tape retains
/// `O(c^2)` row concatenations — the ~600 MiB/layer problem). This does the
/// SAME substitution at block granularity: the outer recurrence
/// `X_i = (I - A_ii)^{-1} (B_i + sum_{k<i} A_ik X_k)` over `c/8` block rows
/// keeps the reference's stability (errors do not compound with the inverse's
/// magnitude), while the tiny 8x8 diagonal inverses use nilpotent doubling
/// (exact in 3 matmuls, growth bounded by the block width). Measured on the
/// real 0.8B: flat ~5e-5 logit parity at every position, where the explicit
/// full-chunk inverse degraded to 1.1e-2 by position 22.
fn ut_solve(a: &Tensor, b_rhs: &Tensor) -> CandleResult<Tensor> {
    let c = a.dim(D::Minus1)?;
    if a.dim(D::Minus2)? != c || b_rhs.dim(D::Minus2)? != c {
        bail!(
            "ut_solve: A must be [.., c, c] and B [.., c, r], got {:?} / {:?}",
            a.dims(),
            b_rhs.dims()
        );
    }
    if c <= UT_SOLVE_BLOCK {
        return bmm(&ut_inverse(a, c)?, b_rhs);
    }
    let nb = c.div_ceil(UT_SOLVE_BLOCK);
    let mut xs: Vec<Tensor> = Vec::with_capacity(nb);
    for bi in 0..nb {
        let r0 = bi * UT_SOLVE_BLOCK;
        let rw = UT_SOLVE_BLOCK.min(c - r0);
        let a_rows = a.narrow(D::Minus2, r0, rw)?;
        let mut rhs = b_rhs.narrow(D::Minus2, r0, rw)?.contiguous()?;
        // rhs += sum_{k < bi} A[block i, block k] @ X[block k] — A is
        // strictly lower, so only blocks left of the diagonal contribute.
        for (k, xk) in xs.iter().enumerate() {
            let c0 = k * UT_SOLVE_BLOCK;
            let cw = UT_SOLVE_BLOCK.min(c - c0);
            let a_ik = a_rows.narrow(D::Minus1, c0, cw)?.contiguous()?;
            rhs = (rhs + bmm(&a_ik, xk)?)?;
        }
        let a_ii = a_rows.narrow(D::Minus1, r0, rw)?.contiguous()?;
        xs.push(bmm(&ut_inverse(&a_ii, rw)?, &rhs)?);
    }
    Tensor::cat(&xs, D::Minus2)
}

/// The gated delta rule in the **chunked WY form** — the training/prefill
/// kernel. Mathematically identical to [`gated_delta_rule_recurrent`] (float
/// roundoff apart; the cross-check gate pins this), but the sequence is
/// processed in `chunk_size` blocks of dense matmuls, so wall-clock
/// parallelism and autograd memory scale per chunk instead of per token.
///
/// Same layouts and contract as [`gated_delta_rule_recurrent`]; additionally
/// `chunk_size >= 1` (use 64 — the reference default and what the oracle
/// executes; this is a compute-scheduling constant, not a quality knob). The
/// sequence is zero-padded internally to a chunk multiple and the output
/// truncated back. Returns `(output, state)` with `state` `[batch, heads,
/// k_dim, v_dim]` F32 — feeding it back as `initial_state` of either kernel
/// is the prefill→decode handoff (pinned by the handoff gate).
///
/// # Errors
///
/// Returns a candle error on rank/shape mismatches, `chunk_size == 0`, or if
/// an underlying tensor op fails.
pub fn gated_delta_rule_chunked(
    query: &Tensor,
    key: &Tensor,
    value: &Tensor,
    g: &Tensor,
    beta: &Tensor,
    chunk_size: usize,
    initial_state: Option<&Tensor>,
) -> CandleResult<(Tensor, Tensor)> {
    if chunk_size == 0 {
        bail!("gdn: chunk_size must be >= 1");
    }
    let inp = prepare_inputs(query, key, value, g, beta, initial_state)?;
    let (b, h, t, k_dim) = inp.key.dims4()?;
    let v_dim = inp.value.dims4()?.3;
    let c = chunk_size;
    let pad = (c - t % c) % c;
    let total = t + pad;
    let n = total / c;
    let device = inp.query.device().clone();

    let pad_seq = |x: &Tensor| -> CandleResult<Tensor> {
        if pad == 0 {
            Ok(x.clone())
        } else {
            x.pad_with_zeros(2, 0, pad)
        }
    };
    let query = pad_seq(&inp.query)?;
    let key = pad_seq(&inp.key)?;
    let value = pad_seq(&inp.value)?;
    let g = pad_seq(&inp.g)?;
    let beta = pad_seq(&inp.beta)?;

    let v_beta = value.broadcast_mul(&beta.unsqueeze(D::Minus1)?)?;
    let k_beta = key.broadcast_mul(&beta.unsqueeze(D::Minus1)?)?;

    // Reshape to chunks: [B, H, N, C, *] / [B, H, N, C].
    let chunk4 = |x: &Tensor, last: usize| x.reshape((b, h, n, c, last));
    let query = chunk4(&query, k_dim)?;
    let key = chunk4(&key, k_dim)?;
    let v_beta = chunk4(&v_beta, v_dim)?;
    let k_beta = chunk4(&k_beta, k_dim)?;
    let g = g.reshape((b, h, n, c))?;

    // Within-chunk cumulative log-decay and the decay mask
    // exp(g_i - g_j), lower-triangular inclusive (tril -> exp -> tril, so the
    // never-used upper entries are zeroed without exponentiating a positive).
    let g_cum = g.cumsum(D::Minus1)?;
    let tril = Tensor::tril2(c, DType::F32, &device)?;
    let diff = g_cum
        .unsqueeze(D::Minus1)?
        .broadcast_sub(&g_cum.unsqueeze(D::Minus2)?)?;
    let decay_mask = diff.broadcast_mul(&tril)?.exp()?.broadcast_mul(&tril)?;

    // UT transform: strictly-lower attn, then the (stable, block-wise)
    // forward substitution applied to both right-hand sides at once.
    let strict = strict_lower_mask(c, &device)?;
    let attn = bmm(&k_beta, &key.transpose(D::Minus1, D::Minus2)?)?
        .broadcast_mul(&decay_mask)?
        .neg()?
        .broadcast_mul(&strict)?;
    let rhs = Tensor::cat(
        &[
            &v_beta,
            &k_beta.broadcast_mul(&g_cum.exp()?.unsqueeze(D::Minus1)?)?,
        ],
        D::Minus1,
    )?;
    let solved = ut_solve(&attn, &rhs)?;
    let u = solved.narrow(D::Minus1, 0, v_dim)?.contiguous()?; // pseudo-values, [B, H, N, C, V]
    let k_cumdecay = solved.narrow(D::Minus1, v_dim, k_dim)?.contiguous()?;

    // Inter-chunk sequential recurrence over N chunks.
    let mut state = inp.state;
    let mut outs: Vec<Tensor> = Vec::with_capacity(n);
    for i in 0..n {
        let q_i = query.narrow(2, i, 1)?.squeeze(2)?.contiguous()?; // [B, H, C, K]
        let k_i = key.narrow(2, i, 1)?.squeeze(2)?.contiguous()?;
        let u_i = u.narrow(2, i, 1)?.squeeze(2)?.contiguous()?; // [B, H, C, V]
        let kcd_i = k_cumdecay.narrow(2, i, 1)?.squeeze(2)?.contiguous()?;
        let g_i = g_cum.narrow(2, i, 1)?.squeeze(2)?.contiguous()?; // [B, H, C]
        let dm_i = decay_mask.narrow(2, i, 1)?.squeeze(2)?.contiguous()?; // [B, H, C, C]

        let attn_local = bmm(&q_i, &k_i.transpose(D::Minus1, D::Minus2)?)?.broadcast_mul(&dm_i)?;
        let v_prime = bmm(&kcd_i, &state)?; // [B, H, C, V]
        let v_new = (u_i - v_prime)?;
        let attn_inter = bmm(
            &q_i.broadcast_mul(&g_i.exp()?.unsqueeze(D::Minus1)?)?,
            &state,
        )?;
        outs.push((attn_inter + bmm(&attn_local, &v_new)?)?);

        let g_last = g_i.narrow(D::Minus1, c - 1, 1)?; // [B, H, 1]
        let state_decay = g_last.exp()?.unsqueeze(D::Minus1)?; // [B, H, 1, 1]
        let k_scaled =
            k_i.broadcast_mul(&g_last.broadcast_sub(&g_i)?.exp()?.unsqueeze(D::Minus1)?)?;
        state = state
            .broadcast_mul(&state_decay)?
            .broadcast_add(&bmm(&k_scaled.transpose(D::Minus1, D::Minus2)?, &v_new)?)?;
    }
    let out = Tensor::stack(&outs, 2)?.reshape((b, h, total, v_dim))?;
    let out = out.narrow(2, 0, t)?;
    let out = out.transpose(1, 2)?.contiguous()?.to_dtype(inp.out_dtype)?;
    Ok((out, state))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::nn::grad_coverage;
    use candle_core::{Device, Var};
    use serde_json::Value;

    /// Committed oracle dumps from the transformers v5.11.0 `qwen3_5` torch
    /// fallbacks (`scripts/oracle/gen_gdn_golden.py`, `ferrl-oracle` env).
    const GOLDEN: &str = include_str!("../tests/fixtures/gdn_golden.json");

    /// Two independent f32 implementations of the same math (different
    /// reduction order), on O(1)-magnitude values.
    const ORACLE_TOL: f32 = 5e-5;

    fn golden() -> Value {
        let g: Value = serde_json::from_str(GOLDEN).expect("gdn golden fixture parses");
        // Pin the oracle version: a silent regeneration under a different
        // transformers release must force a deliberate, reviewable test edit.
        assert_eq!(
            g["meta"]["transformers"], "5.11.0",
            "fixture regenerated under an unexpected transformers version"
        );
        // torch is part of the numeric contract too (the reference kernels
        // run on its CPU stack) — "+cpu" suffix tolerated, 2.12.0 required.
        let torch = g["meta"]["torch"].as_str().expect("fixture torch version");
        assert!(
            torch.starts_with("2.12.0"),
            "fixture regenerated under an unexpected torch version: {torch}"
        );
        g
    }

    fn vecf(v: &Value) -> Vec<f32> {
        v.as_array()
            .expect("fixture array")
            .iter()
            .map(|x| x.as_f64().expect("fixture float") as f32)
            .collect()
    }

    fn usz(c: &Value, key: &str) -> usize {
        c[key]
            .as_u64()
            .unwrap_or_else(|| panic!("fixture usize {key}")) as usize
    }

    fn ten(c: &Value, key: &str, shape: &[usize]) -> Tensor {
        Tensor::from_vec(vecf(&c[key]), shape, &Device::Cpu).expect("fixture tensor")
    }

    fn max_abs_diff(a: &Tensor, b: &Tensor) -> f32 {
        let av: Vec<f32> = a
            .flatten_all()
            .unwrap()
            .to_dtype(DType::F32)
            .unwrap()
            .to_vec1()
            .unwrap();
        let bv: Vec<f32> = b
            .flatten_all()
            .unwrap()
            .to_dtype(DType::F32)
            .unwrap()
            .to_vec1()
            .unwrap();
        assert_eq!(av.len(), bv.len(), "tensor length mismatch");
        av.iter()
            .zip(&bv)
            .map(|(x, y)| (x - y).abs())
            .fold(0.0, f32::max)
    }

    struct GdnCase {
        q: Tensor,
        k: Tensor,
        v: Tensor,
        g: Tensor,
        beta: Tensor,
        init: Option<Tensor>,
        out: Tensor,
        state: Tensor,
    }

    fn gdn_case(name: &str) -> GdnCase {
        let g = golden();
        let c = &g["cases"][name];
        assert!(!c.is_null(), "fixture case {name} present");
        let (b, t, h, kd, vd) = (
            usz(c, "b"),
            usz(c, "t"),
            usz(c, "h"),
            usz(c, "k"),
            usz(c, "v"),
        );
        GdnCase {
            q: ten(c, "query", &[b, t, h, kd]),
            k: ten(c, "key", &[b, t, h, kd]),
            v: ten(c, "value", &[b, t, h, vd]),
            g: ten(c, "g", &[b, t, h]),
            beta: ten(c, "beta", &[b, t, h]),
            init: c
                .get("initial_state")
                .filter(|x| !x.is_null())
                .map(|_| ten(c, "initial_state", &[b, h, kd, vd])),
            out: ten(c, "out", &[b, t, h, vd]),
            state: ten(c, "state", &[b, h, kd, vd]),
        }
    }

    /// Deterministic pseudo-random vec in [-1, 1] (xorshift; no rand dep here).
    fn det(seed: u64, n: usize) -> Vec<f32> {
        let mut s = seed.wrapping_mul(0x9E37_79B9_7F4A_7C15) | 1;
        (0..n)
            .map(|_| {
                s ^= s << 13;
                s ^= s >> 7;
                s ^= s << 17;
                ((s >> 11) as f64 / (1u64 << 53) as f64 * 2.0 - 1.0) as f32
            })
            .collect()
    }

    /// Deterministic, realistically-ranged kernel inputs: beta in (0, 1),
    /// g <= 0 (log-space decay).
    fn det_inputs(
        seed: u64,
        b: usize,
        t: usize,
        h: usize,
        kd: usize,
        vd: usize,
    ) -> (Tensor, Tensor, Tensor, Tensor, Tensor) {
        let dev = Device::Cpu;
        let q = Tensor::from_vec(det(seed, b * t * h * kd), (b, t, h, kd), &dev).unwrap();
        let k = Tensor::from_vec(det(seed + 1, b * t * h * kd), (b, t, h, kd), &dev).unwrap();
        let v = Tensor::from_vec(det(seed + 2, b * t * h * vd), (b, t, h, vd), &dev).unwrap();
        let g_raw: Vec<f32> = det(seed + 3, b * t * h)
            .into_iter()
            .map(|u| -(0.2 + 0.8 * u.abs()))
            .collect();
        let beta_raw: Vec<f32> = det(seed + 4, b * t * h)
            .into_iter()
            .map(|u| 0.5 + 0.4 * u)
            .collect();
        let g = Tensor::from_vec(g_raw, (b, t, h), &dev).unwrap();
        let beta = Tensor::from_vec(beta_raw, (b, t, h), &dev).unwrap();
        (q, k, v, g, beta)
    }

    /// THE oracle gate, recurrent form: output and final state match the
    /// transformers reference dumps at every element, with and without an
    /// initial state.
    #[test]
    fn recurrent_matches_transformers_oracle() {
        for name in ["recurrent_no_state", "recurrent_with_state"] {
            let c = gdn_case(name);
            let (out, state) =
                gated_delta_rule_recurrent(&c.q, &c.k, &c.v, &c.g, &c.beta, c.init.as_ref())
                    .unwrap();
            let d_out = max_abs_diff(&out, &c.out);
            let d_state = max_abs_diff(&state, &c.state);
            assert!(d_out <= ORACLE_TOL, "{name}: out diff {d_out}");
            assert!(d_state <= ORACLE_TOL, "{name}: state diff {d_state}");
        }
    }

    /// THE oracle gate, chunked form — t=130 crosses two chunk boundaries
    /// (exercises padding + the inter-chunk recurrence), t=70 adds an initial
    /// state through the chunked path.
    #[test]
    fn chunked_matches_transformers_oracle() {
        for name in ["chunked_t130", "chunked_with_state"] {
            let c = gdn_case(name);
            let (out, state) =
                gated_delta_rule_chunked(&c.q, &c.k, &c.v, &c.g, &c.beta, 64, c.init.as_ref())
                    .unwrap();
            let d_out = max_abs_diff(&out, &c.out);
            let d_state = max_abs_diff(&state, &c.state);
            assert!(d_out <= ORACLE_TOL, "{name}: out diff {d_out}");
            assert!(d_state <= ORACLE_TOL, "{name}: state diff {d_state}");
        }
    }

    /// Non-vacuity: the oracle gate must have teeth. Perturbing the decay or
    /// the query scale by a few percent must blow well past the tolerance —
    /// if it doesn't, the gate is decoration (the M1 vacuous-rope lesson).
    #[test]
    fn oracle_gate_has_teeth_under_perturbations() {
        let c = gdn_case("recurrent_no_state");
        let g_bumped = (&c.g + 0.05).unwrap();
        let (out, _) =
            gated_delta_rule_recurrent(&c.q, &c.k, &c.v, &g_bumped, &c.beta, None).unwrap();
        let d = max_abs_diff(&out, &c.out);
        assert!(d > ORACLE_TOL * 10.0, "decay perturbation invisible: {d}");

        // q is l2-normalized inside, so a uniform scale is invisible BY
        // DESIGN — perturb a single element instead (breaks the direction).
        let dims = c.q.dims4().unwrap();
        let one = Tensor::ones((1, 1, 1, 1), DType::F32, &Device::Cpu)
            .unwrap()
            .pad_with_zeros(3, 0, dims.3 - 1)
            .unwrap()
            .pad_with_zeros(2, 0, dims.2 - 1)
            .unwrap()
            .pad_with_zeros(1, 0, dims.1 - 1)
            .unwrap()
            .pad_with_zeros(0, 0, dims.0 - 1)
            .unwrap();
        let q_bumped = (&c.q + one).unwrap();
        let (out_b, _) =
            gated_delta_rule_recurrent(&q_bumped, &c.k, &c.v, &c.g, &c.beta, None).unwrap();
        let d_b = max_abs_diff(&out_b, &c.out);
        assert!(
            d_b > ORACLE_TOL * 10.0,
            "query perturbation invisible: {d_b}"
        );

        // Margin pin: even a TINY decay perturbation (1e-3) must exceed the
        // tolerance — this bounds how far ORACLE_TOL could silently loosen
        // before the gate stops constraining anything.
        let g_tiny = (&c.g + 1e-3).unwrap();
        let (out_t, _) =
            gated_delta_rule_recurrent(&c.q, &c.k, &c.v, &g_tiny, &c.beta, None).unwrap();
        let d_t = max_abs_diff(&out_t, &c.out);
        assert!(
            d_t > ORACLE_TOL,
            "1e-3 decay perturbation must exceed tol: {d_t}"
        );

        // And the uniform-scale invariance itself is a property worth pinning:
        let q_scaled = (&c.q * 1.05).unwrap();
        let (out_s, _) =
            gated_delta_rule_recurrent(&q_scaled, &c.k, &c.v, &c.g, &c.beta, None).unwrap();
        let d_s = max_abs_diff(&out_s, &c.out);
        assert!(
            d_s <= ORACLE_TOL,
            "l2norm must absorb a uniform q scale: {d_s}"
        );
    }

    /// The two kernels are independent ports of the same math: they must
    /// agree to float roundoff across t < chunk (padding path), t spanning
    /// multiple chunks, and t == 1 (the decode shape).
    #[test]
    fn chunked_equals_recurrent_cross_check() {
        for (seed, b, t, h, kd, vd) in [
            (11, 2, 3, 2, 4, 6),
            (12, 1, 70, 2, 3, 5),
            (13, 2, 1, 1, 4, 4),
            (14, 1, 64, 2, 4, 4),
        ] {
            let (q, k, v, g, beta) = det_inputs(seed, b, t, h, kd, vd);
            let (out_r, st_r) = gated_delta_rule_recurrent(&q, &k, &v, &g, &beta, None).unwrap();
            let (out_c, st_c) = gated_delta_rule_chunked(&q, &k, &v, &g, &beta, 64, None).unwrap();
            let d_out = max_abs_diff(&out_r, &out_c);
            let d_st = max_abs_diff(&st_r, &st_c);
            assert!(d_out <= ORACLE_TOL, "t={t}: out diff {d_out}");
            assert!(d_st <= ORACLE_TOL, "t={t}: state diff {d_st}");
        }
    }

    /// The cached-rollout handoff: chunked prefill over the prompt, then
    /// recurrent decode from the returned state, must equal the full-sequence
    /// run — this is exactly what the merged decoder will do.
    #[test]
    fn chunked_prefill_then_recurrent_decode_matches_full() {
        let (b, t, h, kd, vd) = (2usize, 10usize, 2usize, 4usize, 5usize);
        let split = 7usize;
        let (q, k, v, g, beta) = det_inputs(21, b, t, h, kd, vd);
        let (out_full, st_full) = gated_delta_rule_recurrent(&q, &k, &v, &g, &beta, None).unwrap();

        let head = |x: &Tensor| x.narrow(1, 0, split).unwrap().contiguous().unwrap();
        let tail = |x: &Tensor| x.narrow(1, split, t - split).unwrap().contiguous().unwrap();
        let (out_pre, st_pre) = gated_delta_rule_chunked(
            &head(&q),
            &head(&k),
            &head(&v),
            &head(&g),
            &head(&beta),
            64,
            None,
        )
        .unwrap();
        let (out_dec, st_dec) = gated_delta_rule_recurrent(
            &tail(&q),
            &tail(&k),
            &tail(&v),
            &tail(&g),
            &tail(&beta),
            Some(&st_pre),
        )
        .unwrap();

        let d_pre = max_abs_diff(&out_pre, &out_full.narrow(1, 0, split).unwrap());
        let d_dec = max_abs_diff(&out_dec, &out_full.narrow(1, split, t - split).unwrap());
        let d_st = max_abs_diff(&st_dec, &st_full);
        assert!(d_pre <= ORACLE_TOL, "prefill segment diff {d_pre}");
        assert!(d_dec <= ORACLE_TOL, "decode segment diff {d_dec}");
        assert!(d_st <= ORACLE_TOL, "final state diff {d_st}");
    }

    /// Both kernels are tape-bearing end to end: gradients reach q, k, v, g,
    /// AND beta (all five), finite and nonzero.
    #[test]
    fn both_kernels_carry_gradients_to_all_inputs() {
        let (b, t, h, kd, vd) = (1usize, 5usize, 2usize, 3usize, 4usize);
        for chunked in [false, true] {
            let (q0, k0, v0, g0, beta0) = det_inputs(31, b, t, h, kd, vd);
            let vars: Vec<Var> = [&q0, &k0, &v0, &g0, &beta0]
                .iter()
                .map(|x| Var::from_tensor(x).unwrap())
                .collect();
            let (out, _state) = if chunked {
                gated_delta_rule_chunked(
                    vars[0].as_tensor(),
                    vars[1].as_tensor(),
                    vars[2].as_tensor(),
                    vars[3].as_tensor(),
                    vars[4].as_tensor(),
                    4, // small chunk so t=5 also exercises the inter-chunk path
                    None,
                )
                .unwrap()
            } else {
                gated_delta_rule_recurrent(
                    vars[0].as_tensor(),
                    vars[1].as_tensor(),
                    vars[2].as_tensor(),
                    vars[3].as_tensor(),
                    vars[4].as_tensor(),
                    None,
                )
                .unwrap()
            };
            let loss = out.sqr().unwrap().sum_all().unwrap();
            let grads = loss.backward().unwrap();
            let cov = grad_coverage(&vars, &grads).unwrap();
            assert!(cov.is_ok(), "chunked={chunked}: {cov:?}");
            assert_eq!(
                cov.nonzero, 5,
                "chunked={chunked}: every input must carry gradient: {cov:?}"
            );
        }
    }

    /// Conv oracle gate: both fixture cases (zero left pad / explicit left
    /// context) match `F.conv1d(groups=C)` element-wise.
    #[test]
    fn conv_matches_transformers_oracle() {
        let g = golden();
        for name in ["conv_no_ctx", "conv_with_ctx"] {
            let c = &g["cases"][name];
            let (b, ch, l, kernel) = (usz(c, "b"), usz(c, "c"), usz(c, "l"), usz(c, "kernel"));
            let x = ten(c, "x", &[b, ch, l]);
            let w = ten(c, "weight", &[ch, kernel]);
            let want = ten(c, "out", &[b, ch, l]);
            let left = c
                .get("left")
                .filter(|v| !v.is_null())
                .map(|_| ten(c, "left", &[b, ch, kernel - 1]));
            let got = causal_depthwise_conv1d(&x, &w, left.as_ref()).unwrap();
            let d = max_abs_diff(&got, &want);
            assert!(d <= 1e-5, "{name}: diff {d}");
        }
    }

    /// The conv caching contract: continuing with the last `kernel - 1`
    /// PRE-ACTIVATION INPUTS as left context equals the full-sequence conv;
    /// the two planted state bugs (state from conv OUTPUTS; state after `SiLU`)
    /// must both be caught.
    #[test]
    fn conv_left_context_handoff_and_planted_state_bugs() {
        let (b, ch, l, kernel) = (2usize, 5usize, 12usize, 4usize);
        let split = 8usize;
        let dev = Device::Cpu;
        let x = Tensor::from_vec(det(41, b * ch * l), (b, ch, l), &dev).unwrap();
        let w = Tensor::from_vec(det(42, ch * kernel), (ch, kernel), &dev).unwrap();
        let full = causal_depthwise_conv1d(&x, &w, None).unwrap();

        let prefix = x.narrow(2, 0, split).unwrap();
        let suffix = x.narrow(2, split, l - split).unwrap().contiguous().unwrap();
        let y_pre = causal_depthwise_conv1d(&prefix, &w, None).unwrap();

        // Correct state: the last kernel-1 INPUT columns of the prefix.
        let state = prefix
            .narrow(2, split - (kernel - 1), kernel - 1)
            .unwrap()
            .contiguous()
            .unwrap();
        let y_suf = causal_depthwise_conv1d(&suffix, &w, Some(&state)).unwrap();
        let stitched = Tensor::cat(&[&y_pre, &y_suf], 2).unwrap();
        let d = max_abs_diff(&stitched, &full);
        assert!(d <= 1e-6, "input-state handoff diff {d}");

        // Planted bug 1: state taken from conv OUTPUTS.
        let bad_out_state = y_pre
            .narrow(2, split - (kernel - 1), kernel - 1)
            .unwrap()
            .contiguous()
            .unwrap();
        let y_bad1 = causal_depthwise_conv1d(&suffix, &w, Some(&bad_out_state)).unwrap();
        let d1 = max_abs_diff(&y_bad1, &full.narrow(2, split, l - split).unwrap());
        assert!(d1 > 1e-3, "output-as-state bug must be visible: {d1}");

        // Planted bug 2: state stored post-SiLU.
        let bad_silu_state = state.silu().unwrap();
        let y_bad2 = causal_depthwise_conv1d(&suffix, &w, Some(&bad_silu_state)).unwrap();
        let d2 = max_abs_diff(&y_bad2, &full.narrow(2, split, l - split).unwrap());
        assert!(d2 > 1e-3, "post-SiLU-state bug must be visible: {d2}");
    }

    /// Softplus oracle gate, including the ±100 stability pins; the naive
    /// `ln(exp(x) + 1)` overflows at x = 100 (why the stable form exists);
    /// gradient is finite across the whole range.
    #[test]
    fn softplus_matches_oracle_and_is_stable() {
        let g = golden();
        let c = &g["cases"]["softplus"];
        let n = vecf(&c["x"]).len();
        let x = ten(c, "x", &[n]);
        let want = ten(c, "out", &[n]);
        let got = stable_softplus(&x).unwrap();
        let d = max_abs_diff(&got, &want);
        assert!(d <= 1e-5, "softplus diff {d}");
        let vals: Vec<f32> = got.to_vec1().unwrap();
        assert!(
            vals.iter().all(|v| v.is_finite()),
            "stable softplus finite: {vals:?}"
        );

        // The naive composite overflows forward at x = 100 — the necessity pin.
        let naive = (x.exp().unwrap() + 1.0).unwrap().log().unwrap();
        let nv: Vec<f32> = naive.to_vec1().unwrap();
        assert!(
            nv.iter().any(|v| !v.is_finite()),
            "naive softplus should overflow somewhere on this range: {nv:?}"
        );

        // Gradient finite and nonzero across the range.
        let xv = Var::from_tensor(&x).unwrap();
        let loss = stable_softplus(xv.as_tensor()).unwrap().sum_all().unwrap();
        let grads = loss.backward().unwrap();
        let gx = grads.get(xv.as_tensor()).expect("softplus grad present");
        let gv: Vec<f32> = gx.to_vec1().unwrap();
        assert!(
            gv.iter().all(|v| v.is_finite()),
            "softplus grad finite: {gv:?}"
        );
        assert!(gv.iter().any(|v| *v > 0.0), "softplus grad live: {gv:?}");
    }

    /// l2norm oracle gate on O(1) and small-magnitude rows; the
    /// eps-on-the-norm planted variant must be caught on the small rows
    /// (near zero is exactly where the convention matters).
    #[test]
    fn l2norm_matches_oracle_and_convention_is_load_bearing() {
        let g = golden();
        for name in ["l2norm", "l2norm_small"] {
            let c = &g["cases"][name];
            let (rows, dim) = (usz(c, "rows"), usz(c, "dim"));
            let x = ten(c, "x", &[rows, dim]);
            let want = ten(c, "out", &[rows, dim]);
            let got = l2norm(&x, 1e-6).unwrap();
            let d = max_abs_diff(&got, &want);
            assert!(d <= 1e-6, "{name}: diff {d}");
        }
        // Planted: x / (||x|| + eps) — visibly wrong on the small rows.
        let c = &golden()["cases"]["l2norm_small"];
        let x = ten(c, "x", &[usz(c, "rows"), usz(c, "dim")]);
        let want = ten(c, "out", &[usz(c, "rows"), usz(c, "dim")]);
        let norm = x
            .sqr()
            .unwrap()
            .sum_keepdim(D::Minus1)
            .unwrap()
            .sqrt()
            .unwrap();
        let wrong = x.broadcast_div(&(norm + 1e-6).unwrap()).unwrap();
        let d = max_abs_diff(&wrong, &want);
        assert!(d > 1e-4, "eps-on-norm planted bug must be visible: {d}");
    }

    /// Fail-loud shape validation: mismatched dims, bad state, zero chunk.
    #[test]
    fn kernels_fail_loud_on_bad_shapes() {
        let (q, k, v, g, beta) = det_inputs(51, 1, 4, 2, 3, 5);
        let bad_beta = Tensor::zeros((1, 4, 3), DType::F32, &Device::Cpu).unwrap();
        assert!(gated_delta_rule_recurrent(&q, &k, &v, &g, &bad_beta, None).is_err());
        let bad_state = Tensor::zeros((1, 2, 3, 4), DType::F32, &Device::Cpu).unwrap();
        assert!(gated_delta_rule_recurrent(&q, &k, &v, &g, &beta, Some(&bad_state)).is_err());
        assert!(gated_delta_rule_chunked(&q, &k, &v, &g, &beta, 0, None).is_err());
        let bad_key = Tensor::zeros((1, 4, 2, 4), DType::F32, &Device::Cpu).unwrap();
        assert!(gated_delta_rule_chunked(&q, &bad_key, &v, &g, &beta, 64, None).is_err());
        let bad_w = Tensor::zeros((3, 4), DType::F32, &Device::Cpu).unwrap();
        let x = Tensor::zeros((1, 5, 6), DType::F32, &Device::Cpu).unwrap();
        assert!(causal_depthwise_conv1d(&x, &bad_w, None).is_err());
    }

    /// Strong cumulative decay: at g ≈ -2.2 per token over a full 64-chunk,
    /// `exp(g_cum)` underflows f32 (the chunked form exponentiates CUMULATIVE
    /// decay; the recurrent form only per-token decay) — the two kernels must
    /// still agree through the underflow regime.
    #[test]
    fn cross_check_survives_cumulative_decay_underflow() {
        let (b, t, h, kd, vd) = (1usize, 64usize, 1usize, 3usize, 3usize);
        let (q, k, v, _g, beta) = det_inputs(71, b, t, h, kd, vd);
        let g_raw: Vec<f32> = det(72, b * t * h)
            .into_iter()
            .map(|u| -(2.2 + 0.3 * u))
            .collect();
        let g = Tensor::from_vec(g_raw, (b, t, h), &Device::Cpu).unwrap();
        let (out_r, st_r) = gated_delta_rule_recurrent(&q, &k, &v, &g, &beta, None).unwrap();
        let (out_c, st_c) = gated_delta_rule_chunked(&q, &k, &v, &g, &beta, 64, None).unwrap();
        let d_out = max_abs_diff(&out_r, &out_c);
        let d_st = max_abs_diff(&st_r, &st_c);
        assert!(d_out <= ORACLE_TOL, "underflow regime out diff {d_out}");
        assert!(d_st <= ORACLE_TOL, "underflow regime state diff {d_st}");
        let ov: Vec<f32> = out_c.flatten_all().unwrap().to_vec1().unwrap();
        assert!(
            ov.iter().all(|x| x.is_finite()),
            "no NaN/Inf through underflow"
        );
    }

    /// Finite-difference gradcheck on BOTH kernels: central differences over
    /// every element of every input vs the autograd gradients, on a tiny
    /// config whose loss touches output AND final state (so every decay path
    /// is on the tape). This upgrades the grad gates from liveness probes to
    /// value-correctness gates.
    #[test]
    fn finite_difference_gradcheck_both_kernels() {
        let (b, h, kd, vd) = (1usize, 1usize, 2usize, 2usize);
        let dev = Device::Cpu;

        // (chunk_size, t): 0 = the recurrent kernel; chunk 2 keeps the FD
        // surface tiny; chunk 12 at t = 12 crosses the `ut_solve` block
        // boundary (c = 12 > UT_SOLVE_BLOCK = 8), putting the block forward
        // substitution itself on the FD-checked tape.
        for (chunk_size, t) in [(0usize, 3usize), (2, 3), (12, 12)] {
            let chunked = chunk_size > 0;
            // Fixed projection weights make the scalar loss generic (no
            // symmetry).
            let w_out = Tensor::from_vec(det(81, b * t * h * vd), (b, t, h, vd), &dev).unwrap();
            let w_st = Tensor::from_vec(det(82, b * h * kd * vd), (b, h, kd, vd), &dev).unwrap();

            let run =
                |q: &Tensor, k: &Tensor, v: &Tensor, g: &Tensor, be: &Tensor| -> (Tensor, Tensor) {
                    if chunked {
                        gated_delta_rule_chunked(q, k, v, g, be, chunk_size, None).unwrap()
                    } else {
                        gated_delta_rule_recurrent(q, k, v, g, be, None).unwrap()
                    }
                };
            let loss_of = |q: &Tensor, k: &Tensor, v: &Tensor, g: &Tensor, be: &Tensor| -> Tensor {
                let (out, st) = run(q, k, v, g, be);
                ((out * &w_out).unwrap().sum_all().unwrap()
                    + (st * &w_st).unwrap().sum_all().unwrap())
                .unwrap()
            };

            let (q0, k0, v0, g0, b0) = det_inputs(91, b, t, h, kd, vd);
            let inputs = [&q0, &k0, &v0, &g0, &b0];
            let vars: Vec<Var> = inputs
                .iter()
                .map(|x| Var::from_tensor(x).unwrap())
                .collect();
            let loss = loss_of(
                vars[0].as_tensor(),
                vars[1].as_tensor(),
                vars[2].as_tensor(),
                vars[3].as_tensor(),
                vars[4].as_tensor(),
            );
            let grads = loss.backward().unwrap();

            let h_step = 1e-2f32;
            for (vi, base) in inputs.iter().enumerate() {
                let ad: Vec<f32> = grads
                    .get(vars[vi].as_tensor())
                    .unwrap_or_else(|| panic!("grad missing for input {vi}"))
                    .flatten_all()
                    .unwrap()
                    .to_vec1()
                    .unwrap();
                let flat: Vec<f32> = base.flatten_all().unwrap().to_vec1().unwrap();
                let dims = base.dims().to_vec();
                for ei in 0..flat.len() {
                    let eval = |delta: f32| -> f32 {
                        let mut pert = flat.clone();
                        pert[ei] += delta;
                        let pt = Tensor::from_vec(pert, dims.as_slice(), &dev).unwrap();
                        let args: Vec<&Tensor> = (0..5)
                            .map(|j| if j == vi { &pt } else { inputs[j] })
                            .collect();
                        loss_of(args[0], args[1], args[2], args[3], args[4])
                            .to_scalar::<f32>()
                            .unwrap()
                    };
                    let fd = (eval(h_step) - eval(-h_step)) / (2.0 * h_step);
                    let tol = 2e-2f32.max(0.05 * fd.abs());
                    assert!(
                        (fd - ad[ei]).abs() <= tol,
                        "chunk={chunk_size} input {vi} elem {ei}: fd {fd} vs autograd {}",
                        ad[ei]
                    );
                }
            }
        }
    }

    #[test]
    #[allow(clippy::print_stderr)] // the measured error gap is the calibration record
    fn ut_solve_is_stable_where_the_explicit_inverse_degrades() {
        // The real-0.8B regression this guards (2026-06-11): strongly-coupled
        // keys (repeated/related tokens) under weak decay make the UT
        // inverse's entries grow with row index; the explicit binary-doubling
        // inverse amplifies its rounding by that magnitude (not backward
        // stable), which surfaced as logit divergence growing exponentially
        // along the sequence (1.1e-2 by position 22, vs flat ~5e-5 from the
        // stable solver). This pins ut_solve against an F64 ground truth in
        // exactly that regime — and pins the GAP, so a "simplification" back
        // to the explicit inverse fails here before it reaches a model gate.
        let dev = Device::Cpu;
        let c = 24usize;
        let kdim = 16usize;
        // Correlated unit keys: one base direction + small noise, l2-normed —
        // pairwise inner products ~0.9, the strong-coupling regime.
        let base = Tensor::from_vec(det(7, kdim), (1, kdim), &dev).unwrap();
        let noise = (Tensor::from_vec(det(8, c * kdim), (c, kdim), &dev).unwrap() * 0.3).unwrap();
        let keys = l2norm(&base.broadcast_add(&noise).unwrap(), 1e-6).unwrap();
        let strict = strict_lower_mask(c, &dev).unwrap();
        let a32 = (keys.matmul(&keys.t().unwrap()).unwrap() * (-0.85))
            .unwrap()
            .broadcast_mul(&strict)
            .unwrap()
            .unsqueeze(0)
            .unwrap(); // [1, c, c]
        let b32 = Tensor::from_vec(det(9, c * 4), (1, c, 4), &dev).unwrap();
        let a64 = a32.to_dtype(DType::F64).unwrap();
        let b64 = b32.to_dtype(DType::F64).unwrap();

        // F64 ground truth (the stable solver at ~2^29x the precision).
        let truth = ut_solve(&a64, &b64).unwrap();
        let scale: f64 = truth
            .abs()
            .unwrap()
            .flatten_all()
            .unwrap()
            .max(0)
            .unwrap()
            .to_scalar()
            .unwrap();
        let rel_err = |x: &Tensor| -> f64 {
            let d: f64 = x
                .to_dtype(DType::F64)
                .unwrap()
                .broadcast_sub(&truth)
                .unwrap()
                .abs()
                .unwrap()
                .flatten_all()
                .unwrap()
                .max(0)
                .unwrap()
                .to_scalar()
                .unwrap();
            d / scale
        };

        let solve_rel = rel_err(&ut_solve(&a32, &b32).unwrap());
        let explicit_rel = rel_err(&bmm(&ut_inverse(&a32, c).unwrap(), &b32).unwrap());
        eprintln!(
            "[ut_solve stability] F32-vs-F64 relative error: block solve {solve_rel:e}, \
             explicit inverse {explicit_rel:e} (solution scale {scale:.2e})"
        );
        // Measured 2026-06-11: block solve ~1e-7 class, explicit inverse
        // orders of magnitude worse in this regime. Both bounds have wide
        // headroom; the GAP assert is the real regression tooth.
        assert!(
            solve_rel <= 1e-5,
            "block forward substitution lost precision: rel {solve_rel:e}"
        );
        assert!(
            solve_rel * 10.0 <= explicit_rel,
            "the stability gap collapsed (solve {solve_rel:e} vs explicit {explicit_rel:e}) — \
             if the explicit inverse got this accurate, this regime is no longer adversarial; \
             rebuild the case before trusting it"
        );
    }

    /// Dtype contract: bf16 in → bf16 out, state F32, both kernels — and the
    /// bf16 path stays close to the f32 one.
    #[test]
    fn output_dtype_follows_query_and_state_stays_f32() {
        let (q, k, v, g, beta) = det_inputs(61, 1, 6, 2, 4, 4);
        let to_bf = |x: &Tensor| x.to_dtype(DType::BF16).unwrap();
        for chunked in [false, true] {
            let (out, state) = if chunked {
                gated_delta_rule_chunked(&to_bf(&q), &to_bf(&k), &to_bf(&v), &g, &beta, 4, None)
                    .unwrap()
            } else {
                gated_delta_rule_recurrent(&to_bf(&q), &to_bf(&k), &to_bf(&v), &g, &beta, None)
                    .unwrap()
            };
            assert_eq!(out.dtype(), DType::BF16, "chunked={chunked}");
            assert_eq!(state.dtype(), DType::F32, "chunked={chunked}");
            let (out_f, _) = gated_delta_rule_recurrent(&q, &k, &v, &g, &beta, None).unwrap();
            let d = max_abs_diff(&out, &out_f);
            assert!(d <= 0.05, "bf16 path diverged: {d}");
        }
    }
}
