//! # ferrl
//!
//! `ferrl` is a [candle](https://github.com/huggingface/candle)-native,
//! RL-driven discovery platform. Given a typed task with a verifiable reward and
//! a language-model policy, it samples candidates, improves the policy with
//! reinforcement learning, verifies candidates, and retains the best supported
//! artifact. [GRPO](https://arxiv.org/abs/2402.03300) + `LoRA` is the first
//! recipe; [`trimul`] GPU-kernel discovery is the first artifact task.
//!
//! The CLI has a closed built-in registry for [`countdown`], [`math`], and
//! [`trimul`]. Rust callers can compose custom typed tasks from [`sample`],
//! [`reward`], [`policy`], and [`trainer`] while the pre-`1.0` surface evolves.
//!
//! ## Owned boundaries
//!
//! - **Tasks and verification:** scalar, fallible [`reward`] functions over
//!   typed [`sample`] values; exact arithmetic reference tasks; the verifier-
//!   backed [`trimul`] reward; and the [`sandbox`] / [`verifier_executor`]
//!   execution tiers for untrusted generated code.
//! - **RL and trainable state:** pure [`grpo`] math, the generic [`trainer`],
//!   manual [`lora`] adapters, opt-in full fine-tuning, [`optim`], reproducible
//!   [`sampler`] state, held-out [`eval`], and layer-boundary [`remat`].
//! - **Durability and provenance:** identity-bound ordinary [`checkpoint`]
//!   packages, the versioned separated [`rollout_ledger`] contract, and
//!   [`telemetry`] for launch/config identity, metrics, candidate rows, and
//!   held-out reports. The [`discovery`] facade adds generic local launch and
//!   candidate authentication plus manifest-last accepted-artifact publication;
//!   the binary retains the stricter task-specific TriMul audit boundary.
//! - **Model generality:** [`model`] and [`policy`] define the grad-forward,
//!   cached-decoder, generation, and token-scoring contracts. [`lm_policy`]
//!   instantiates them for Qwen3, dense Llama-3.x, Qwen3.5/3.6 dense and `MoE`,
//!   and dense Gemma 4 text; [`loader`] provides the supported automatic
//!   checkpoint dispatch.
//! - **Distributed execution:** [`comm`] and [`tensor_parallel`] keep world-one,
//!   data-parallel, and supported tensor-parallel paths on one coordination
//!   contract. The optional NCCL bridge contains the crate's only gated
//!   `unsafe`; default builds remain `unsafe`-free.
//! - **Operational compatibility:** [`cuda_compat`] turns PTX/driver mismatches
//!   into actionable diagnostics.
//!
//! `candle-core`, `candle-nn`, and `candle-transformers` remain the compute
//! substrate: tensors, autograd, GPU primitives, and shipped inference
//! implementations. Ferrl builds its differentiable loss and grad-bearing model
//! paths from candle operations rather than implementing another autodiff engine.
//!
//! ## Correctness oracles
//!
//! GRPO is pinned two ways: a `NumPy` fixture covers independent scalar math and
//! advantage normalization, while a fixture generated by TRL 1.5.1's own
//! `GRPOTrainer._compute_loss` covers Ferrl's differentiable clipped/KL loss and
//! GRPO, Dr.GRPO, DAPO, token-level, and sequence-level variants. A grad-coverage
//! canary rejects trainable variables missing from candle's gradient store, and
//! finite-difference tests pin the production loss gradient.
//!
//! Native model forwards are checked position-by-position against committed
//! official-reference fixtures for Qwen3, Llama-3.x, Qwen3.5/3.6, and dense
//! Gemma 4 text. Cached decoders, distributed execution, checkpoints, rollout
//! ledgers, verifier isolation, held-out evaluation, and artifact publication
//! retain separate positive and fail-closed negative-control gates.
//!
//! ## Stability
//!
//! Pre-`1.0`: the public surface may change between minor versions.
//
// `deny`, not `forbid`: the default build compiles **zero** `unsafe` (the lint
// errors on any), but `forbid` cannot be locally overridden, and the
// `--features nccl` NCCL FFI ([`comm`]'s decision-D2 quarantine) needs one
// `#[allow(unsafe_code)]` in its single gated module. That module is not
// compiled without the feature, so the default/CI build is exactly as
// unsafe-free as before; only a GPU-cluster `--features nccl` build carries the
// one allow.
#![deny(unsafe_code)]

pub mod blocks;
pub mod checkpoint;
pub mod comm;
pub mod countdown;
pub mod cuda_compat;
pub mod data;
pub mod dense;
pub mod discovery;
pub mod eval;
mod full_ft;
pub mod gdn;
pub mod gemma4;
pub mod grpo;
pub mod hf;
pub mod llama;
pub mod lm_policy;
pub mod loader;
pub mod lora;
pub mod math;
pub mod model;
pub mod moe;
pub mod nn;
pub mod optim;
pub mod policy;
pub mod qwen;
pub mod qwen35;
pub mod remat;
pub mod reward;
pub mod rollout_ledger;
pub mod sample;
pub mod sampler;
pub mod sandbox;
mod sharded_safetensors;
pub mod telemetry;
pub mod tensor_parallel;
pub mod tokenizer;
pub mod trainer;
pub mod trimul;
pub mod verifier_executor;

#[doc(inline)]
pub use checkpoint::{
    latest_checkpoint, load_adapter, load_checkpoint, save_adapter, save_checkpoint,
    CheckpointBinding, CheckpointError, CheckpointManifest, LatestCheckpoint, LoadedCheckpoint,
    OrdinaryCheckpointIdentity,
};
#[cfg(feature = "nccl")]
pub use comm::RealNccl;
#[doc(inline)]
pub use comm::{Comm, CommError, LocalComm, NcclComm, NcclConfig, NcclPrimitives, SoloComm};
#[doc(inline)]
pub use countdown::{
    build_prompt, generate_dataset, CountdownConfig, CountdownProblem, CountdownReward,
};
#[doc(inline)]
pub use cuda_compat::{check_driver_compat, guard_first_kernel, translate_ptx_error, CompatReport};
#[doc(inline)]
pub use data::{parse_jsonl, read_jsonl, train_eval_split, train_eval_split_by_key, DataError};
#[doc(inline)]
pub use eval::{evaluate, EvalError, EvalReport, PromptEval};

pub use gdn::{
    causal_depthwise_conv1d, gated_delta_rule_chunked, gated_delta_rule_recurrent, l2norm,
    stable_softplus,
};
#[doc(inline)]
pub use gemma4::{
    Gemma4Config, Gemma4FullAttentionRope, Gemma4GradModel, Gemma4LayerType, Gemma4MergedDecoder,
    Gemma4RopeParameters, Gemma4SlidingAttentionRope, Gemma4TextConfig,
    CKPT_PREFIX as GEMMA4_CKPT_PREFIX,
};
#[doc(inline)]
pub use grpo::{
    clipped_surrogate, group_advantages, k3_kl, masked_mean, tis_weight, zero_mask_rows, LossType,
    ScaleRewards, GROUP_STD_EPS,
};
#[doc(inline)]
pub use hf::{
    chatml, checkpoint_eos_from_config, eos_from_config, resolve_checkpoint_eos,
    validate_resolved_eos_consensus, vocab_size_from_config, CheckpointEos, CheckpointEosSelection,
    HfError,
};
#[doc(inline)]
pub use llama::{LlamaGradModel, LlamaMergedDecoder};
#[doc(inline)]
pub use lm_policy::{Gemma4Policy, LlamaPolicy, LmPolicy, Qwen3_5Policy, QwenPolicy};
#[doc(inline)]
pub use loader::{
    checkpoint_policy_sha256, load_auto_policy, load_auto_policy_bound,
    load_auto_policy_with_identity, load_gemma4_policy, load_gemma4_policy_bound,
    load_qwen35_policy_with_targets_bound, load_qwen_policy, load_qwen_policy_bound, AutoPolicy,
    LoaderError, LoaderOpts, PolicyLoadIdentity,
};
#[doc(inline)]
pub use lora::{BaseQuantization, DenseLoraTargets};
#[doc(inline)]
pub use math::{math_prompt, math_split_key, MathProblem, MathReward};
#[doc(inline)]
pub use model::{CachedDecoder, GradModel};
#[doc(inline)]
pub use moe::{moe_experts, sparse_moe_block, topk_router, SparseMoeWeights};
#[doc(inline)]
pub use nn::{grad_coverage, GradCoverage, RmsNorm, RmsNormGated, RmsNormZeroCentered};
#[doc(inline)]
pub use optim::{FerrlAdamW, OptimizerState};
#[doc(inline)]
pub use policy::{EvalSampling, Policy, TensorParallelPolicy};
#[doc(inline)]
pub use qwen::{MergedDecoder, QwenGradModel};
#[doc(inline)]
pub use qwen35::{
    tensors_from_pretrained, varbuilder_from_pretrained, LayerType, LoraTargets, MoeDims,
    Qwen3_5Config, Qwen3_5GradModel, Qwen3_5MergedDecoder, Qwen3_5TextConfig, RopeParameters,
    GDN_CHUNK_SIZE,
};
#[doc(inline)]
pub use remat::{stitched_backward, RematTape};
#[doc(inline)]
pub use reward::{RewardError, RewardFn, RewardOutcome};
#[doc(inline)]
pub use rollout_ledger::{
    DistributedRolloutLedgerStage, LedgerScoreRequirement, RolloutLedgerControls,
    RolloutLedgerError, RolloutLedgerExpectations, RolloutLedgerGroup, RolloutLedgerGroupScope,
    RolloutLedgerIdentity, RolloutLedgerReader, RolloutLedgerRewardStats, RolloutLedgerStep,
    RolloutLedgerWriter, ValidatedRolloutLedgerStep, ROLLOUT_LEDGER_FORMAT_VERSION,
};
#[doc(inline)]
pub use sample::Sample;
#[doc(inline)]
pub use sampler::GrpoSampler;
#[doc(inline)]
pub use sandbox::{
    ApptainerSandbox, Bind, BindMode, NetworkPolicy, ProtectedOutput, ResourceLimits, RunOutcome,
    RunSpec, RunStatus, Sandbox, SandboxError,
};
#[doc(inline)]
pub use telemetry::{
    compare_distributed_metrics, compare_metrics, cuda_memory_snapshot, init_tracing, read_metrics,
    run_span, summarize, Anomaly, DecoderCacheSnapshot, GpuMemoryProbeEvent, GpuMemorySnapshot,
    Metrics, MetricsWriter, ModelTelemetryRecorder, RegressionBudget, RegressionFailure,
    RegressionReport, RunDir, RunSummary,
};
#[doc(inline)]
pub use tensor_parallel::{
    all_reduce_sum_straight_through, column_parallel_linear, concat_column_shards, plan_from_comm,
    row_parallel_linear_partial, row_parallel_linear_partial_from_shard, sum_row_parallel_partials,
    validate_comm_plan, ShardRange, TensorParallelDims, TensorParallelError, TensorParallelPlan,
};
#[doc(inline)]
pub use tokenizer::{HfTokenizer, TokenizerError};
#[doc(inline)]
pub use trainer::{
    RewardGroupScope, RolloutLedgerContinuation, RunStop, ScalarSchedule, SchedulePoint,
    TokenizerLike, Trainer, TrainerConfig, TrainerConfigBuilder, TrainerError,
};
#[doc(inline)]
pub use trimul::{Distribution, TrimulCase, TrimulError, TrimulReward};
#[doc(inline)]
pub use verifier_executor::{
    serve_verifier_executor, SameUidApptainerSandbox, VerifierAssetTransport,
    VerifierExecutorConfig, VerifierExecutorError, VerifierExecutorSandbox,
    VerifierIsolationEvidence, VerifierIsolationTier, VerifierUidBoundary,
    DEFAULT_VERIFIER_EXECUTOR_SOCKET, VERIFIER_ISOLATION_EVIDENCE_VERSION,
};
