//! # ferrl
//!
//! `ferrl` is a [candle](https://github.com/huggingface/candle)-native
//! [GRPO](https://arxiv.org/abs/2402.03300) reinforcement-learning library for
//! RL-fine-tuning large language models in Rust. The first target model is
//! `Qwen3-0.6B-Base`.
//!
//! ## Division of labor
//!
//! `ferrl` owns only the *reinforcement-learning layer*:
//!
//! - the pure GRPO math ([`grpo`]) — advantages, the k3 KL estimator, the
//!   clipped surrogate, and the masked-mean reductions;
//! - the [`reward`] abstraction (scalar rewards, never tensors);
//! - the [`policy`] abstraction over generation and per-token log-probabilities;
//! - a manual `LoRA` adapter ([`lora`]);
//! - run telemetry ([`telemetry`]).
//!
//! Everything below the RL layer — tensors, autograd, optimizers, devices, and
//! the model itself — is **delegated** to `candle-core`, `candle-nn`, and
//! `candle-transformers`. In particular `ferrl` does not implement its own
//! autodiff: it builds a loss [`candle_core::Tensor`] from candle ops and calls
//! [`candle_core::Tensor::backward`].
//!
//! ## Correctness oracles
//!
//! Because the autodiff is not ours, correctness is pinned by oracles rather
//! than by re-deriving gradients: the pure GRPO math is checked against a
//! committed golden JSON fixture generated by an independent Python reference
//! (`scripts/gen_golden.py`); model forwards are later checked against candle's
//! shipped implementation; a grad-coverage canary asserts every trainable `LoRA`
//! [`candle_core::Var`] receives a non-zero gradient after `backward` (candle
//! optimizers *silently* skip params missing from the grad store); and a
//! finite-difference gradcheck validates the loss gradient end-to-end.
//!
//! ## Stability
//!
//! Pre-`1.0`: the public surface may change between minor versions.
#![forbid(unsafe_code)]

pub mod grpo;
pub mod lora;
pub mod policy;
pub mod reward;
pub mod telemetry;

#[doc(inline)]
pub use grpo::{clipped_surrogate, group_advantages, k3_kl, masked_mean, LossType, GROUP_STD_EPS};
#[doc(inline)]
pub use policy::Policy;
#[doc(inline)]
pub use reward::RewardFn;
#[doc(inline)]
pub use telemetry::{init_tracing, Metrics, MetricsWriter, RunDir};
