//! `MoE`-layer primitives for the qwen3.5/3.6 family (M3′) — grad-bearing,
//! line-faithful ports of the transformers v5.11.0 `qwen3_5_moe` reference
//! (`modeling_qwen3_5_moe.py`), pinned against committed dumps
//! (`tests/fixtures/moe_golden.json`, generated by
//! `scripts/oracle/gen_moe_golden.py` in the pinned `ferrl-oracle` env):
//!
//! - [`topk_router`] ← `Qwen3_5MoeTopKRouter.forward` — router logits,
//!   softmax in **F32**, top-k of the *probabilities*, **unconditional
//!   renormalization** over the kept k (this family deletes the
//!   `norm_topk_prob` knob — every member renormalizes; it also deletes
//!   `mlp_only_layers`/`decoder_sparse_step` — every layer is sparse), cast
//!   back to the logits dtype.
//! - [`moe_experts`] ← `Qwen3_5MoeExperts.forward` (the eager fallback) —
//!   the packed-weight expert pass: per HIT expert, gather its tokens, run
//!   `SwiGLU` through that expert's `[2m, h]` / `[h, m]` slices, scale each
//!   token's output by its routing weight, accumulate by index-add (zeros
//!   for tokens an expert does not serve; unhit experts are skipped).
//! - [`sparse_moe_block`] ← `Qwen3_5MoeSparseMoeBlock.forward` — the routed
//!   experts plus a **sigmoid-gated shared expert** (a plain `SwiGLU` MLP at
//!   its own `shared_expert_intermediate_size`).
//!
//! Routing **indices are data-dependent control flow, not gradient**: the
//! per-expert token lists are extracted host-side (the `gdn.rs` chunk-loop
//! pattern), while every value path — logits → probs → kept-k renorm →
//! expert outputs → weighted accumulation — stays on the tape, so a backward
//! through the block reaches the router weight and every hit expert slice
//! (candle's `index_add`/`gather` both carry gradients; `arg_sort` emits
//! integer indices, which the graph walk skips by dtype).
//!
//! Numerics (mirrors the reference exactly): the router softmax runs in F32
//! and the renormalized kept-k weights are cast back to the input dtype;
//! expert and shared-expert matmuls run in the input dtype. Within one
//! `index_add` each destination row receives at most one contribution (top-k
//! experts are distinct per token), so accumulation order cannot reassociate
//! a row; CPU F32 results match the oracle to float roundoff.

use candle_core::{DType, Result as CandleResult, Tensor, D};
use candle_nn::ops::{sigmoid, softmax};

/// The full parameter set of one sparse `MoE` block, in the reference's
/// `[out, in]` linear layout (see [`sparse_moe_block`]).
#[derive(Debug, Clone)]
pub struct SparseMoeWeights<'a> {
    /// Router weight `[experts, hidden]` (no bias).
    pub router: &'a Tensor,
    /// Packed per-expert gate+up `[experts, 2 * moe_inter, hidden]`.
    pub gate_up: &'a Tensor,
    /// Per-expert down `[experts, hidden, moe_inter]`.
    pub down: &'a Tensor,
    /// Shared-expert gate `[shared_inter, hidden]`.
    pub shared_gate: &'a Tensor,
    /// Shared-expert up `[shared_inter, hidden]`.
    pub shared_up: &'a Tensor,
    /// Shared-expert down `[hidden, shared_inter]`.
    pub shared_down: &'a Tensor,
    /// The shared-expert sigmoid gate `[1, hidden]` (no bias).
    pub shared_expert_gate: &'a Tensor,
}

/// The top-k router: `(logits, scores, indices)` for token states `x`
/// (`[tokens, hidden]`) under router `weight` (`[experts, hidden]`).
///
/// Faithful to `Qwen3_5MoeTopKRouter.forward`: `logits = x Wᵀ`; probabilities
/// via a softmax computed in F32; the top `top_k` probabilities are kept and
/// **unconditionally renormalized** to sum to 1 per token, then cast back to
/// the logits dtype. `indices` is `[tokens, top_k]` (u32, descending
/// probability); `scores` aligns with it positionally. The logits and scores
/// are grad-bearing; the indices are not (integer dtype).
///
/// # Errors
///
/// Returns a candle error if shapes are incompatible or `top_k` exceeds the
/// expert count.
pub fn topk_router(
    x: &Tensor,
    weight: &Tensor,
    top_k: usize,
) -> CandleResult<(Tensor, Tensor, Tensor)> {
    let logits = x.matmul(&weight.t()?)?; // [n, E]
    let probs = softmax(&logits.to_dtype(DType::F32)?, D::Minus1)?;
    // Descending arg-sort; ties are measure-zero on real router logits (the
    // gates assert the oracle's indices exactly).
    let order = probs.arg_sort_last_dim(false)?;
    let indices = order.narrow(D::Minus1, 0, top_k)?.contiguous()?;
    let top = probs.gather(&indices, D::Minus1)?;
    let top = top.broadcast_div(&top.sum_keepdim(D::Minus1)?)?;
    let scores = top.to_dtype(logits.dtype())?;
    Ok((logits, scores, indices))
}

/// The packed-weight expert pass over routed tokens.
///
/// Faithful to `Qwen3_5MoeExperts.forward` (the eager fallback): for each
/// expert that serves at least one token, gather its tokens, run `SwiGLU`
/// through that expert's slices of `gate_up` (`[experts, 2m, hidden]`; gate
/// is the first half of the `2m` axis) and `down` (`[experts, hidden, m]`),
/// scale each token's output by its routing weight from `scores`, and
/// accumulate into a zero-initialized output (a token's rows from its top-k
/// experts sum; tokens an expert does not serve are untouched).
///
/// `indices`/`scores` are `[tokens, top_k]` as returned by [`topk_router`].
///
/// The activation is hardcoded `silu` (the family's only shipped
/// `hidden_act`; the model loader rejects anything else at load time).
///
/// # Errors
///
/// Returns a candle error if shapes are incompatible or an index exceeds the
/// expert count.
pub fn moe_experts(
    x: &Tensor,
    gate_up: &Tensor,
    down: &Tensor,
    indices: &Tensor,
    scores: &Tensor,
) -> CandleResult<Tensor> {
    let (num_experts, two_m, _h) = gate_up.dims3()?;
    let m = two_m / 2;
    let k = indices.dim(1)?;
    let device = x.device();

    // Host-side routing table: the indices are control flow, not gradient.
    let flat: Vec<u32> = indices.flatten_all()?.to_vec1()?;
    if let Some(&bad) = flat.iter().find(|&&v| v as usize >= num_experts) {
        candle_core::bail!("moe_experts: routed index {bad} >= {num_experts} experts");
    }
    let scores_flat = scores.flatten_all()?;
    let mut out = x.zeros_like()?;
    for e in 0..num_experts {
        // (token, slot) pairs routed to expert e. A token's top-k experts are
        // distinct, so each destination row gets at most one contribution.
        let routed: Vec<usize> = flat
            .iter()
            .enumerate()
            .filter(|&(_, &v)| v as usize == e)
            .map(|(i, _)| i)
            .collect();
        if routed.is_empty() {
            continue;
        }
        let tok: Vec<u32> = routed.iter().map(|&i| (i / k) as u32).collect();
        let pos: Vec<u32> = routed.iter().map(|&i| i as u32).collect();
        let len = routed.len();
        let tok = Tensor::from_vec(tok, len, device)?;
        let pos = Tensor::from_vec(pos, len, device)?;

        let sel = x.index_select(&tok, 0)?; // [te, h]
        let gu = sel.matmul(&gate_up.get(e)?.t()?)?; // [te, 2m]
        let gate = gu.narrow(D::Minus1, 0, m)?;
        let up = gu.narrow(D::Minus1, m, m)?;
        let act = gate.silu()?.mul(&up.contiguous()?)?; // [te, m]
        let contrib = act.matmul(&down.get(e)?.t()?)?; // [te, h]
        let w = scores_flat.index_select(&pos, 0)?; // [te], grad-bearing
        let contrib = contrib.broadcast_mul(&w.unsqueeze(D::Minus1)?)?;
        out = out.index_add(&tok, &contrib.to_dtype(out.dtype())?, 0)?;
    }
    Ok(out)
}

/// One full sparse `MoE` block: routed experts plus the sigmoid-gated shared
/// expert, over `x` (`[batch, seq, hidden]`).
///
/// Faithful to `Qwen3_5MoeSparseMoeBlock.forward`:
/// `experts(x, idx, w) + sigmoid(x Wgateᵀ) · SwiGLU_shared(x)`, reshaped back
/// to the input geometry. This is the kernel-level composition the model's
/// `MoE` layer menu wires (M3′ PR-2); the dense per-layer MLP stays a separate
/// path.
///
/// # Errors
///
/// Returns a candle error if any weight shape is incompatible.
pub fn sparse_moe_block(
    x: &Tensor,
    weights: &SparseMoeWeights<'_>,
    top_k: usize,
) -> CandleResult<Tensor> {
    let (b, t, h) = x.dims3()?;
    let flat = x.reshape((b * t, h))?;
    // The shared expert: a plain SwiGLU at its own intermediate width.
    let shared = {
        let gate = flat.matmul(&weights.shared_gate.t()?)?.silu()?;
        let up = flat.matmul(&weights.shared_up.t()?)?;
        gate.mul(&up)?.matmul(&weights.shared_down.t()?)?
    };
    let (_logits, scores, indices) = topk_router(&flat, weights.router, top_k)?;
    let experts = moe_experts(&flat, weights.gate_up, weights.down, &indices, &scores)?;
    let gate = sigmoid(&flat.matmul(&weights.shared_expert_gate.t()?)?)?; // [n, 1]
    let out = experts.add(&gate.broadcast_mul(&shared)?)?;
    out.reshape((b, t, h))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::nn::grad_coverage;
    use candle_core::{Device, Var};
    use serde_json::Value;

    /// Committed oracle dumps from the transformers v5.11.0 `qwen3_5_moe`
    /// reference (`scripts/oracle/gen_moe_golden.py`, `ferrl-oracle` env).
    const GOLDEN: &str = include_str!("../tests/fixtures/moe_golden.json");

    /// Two independent f32 implementations of the same math (different
    /// reduction order), on O(1)-magnitude values.
    const ORACLE_TOL: f32 = 5e-5;

    fn golden() -> Value {
        let g: Value = serde_json::from_str(GOLDEN).expect("moe golden fixture parses");
        // Pin the oracle version: a silent regeneration under a different
        // transformers release must force a deliberate, reviewable test edit.
        assert_eq!(
            g["meta"]["transformers"], "5.11.0",
            "fixture regenerated under an unexpected transformers version"
        );
        let torch = g["meta"]["torch"].as_str().expect("fixture torch version");
        assert!(
            torch.starts_with("2.12.0"),
            "fixture regenerated under an unexpected torch version: {torch}"
        );
        g
    }

    fn vecf(v: &Value) -> Vec<f32> {
        v.as_array()
            .expect("fixture array")
            .iter()
            .map(|x| x.as_f64().expect("fixture float") as f32)
            .collect()
    }

    fn veci(v: &Value) -> Vec<u32> {
        v.as_array()
            .expect("fixture array")
            .iter()
            .map(|x| x.as_u64().expect("fixture int") as u32)
            .collect()
    }

    fn usz(c: &Value, key: &str) -> usize {
        c[key]
            .as_u64()
            .unwrap_or_else(|| panic!("fixture usize {key}")) as usize
    }

    fn ten(c: &Value, key: &str, shape: &[usize]) -> Tensor {
        Tensor::from_vec(vecf(&c[key]), shape, &Device::Cpu).expect("fixture tensor")
    }

    fn max_abs_diff(a: &Tensor, b: &Tensor) -> f32 {
        let av: Vec<f32> = a.flatten_all().unwrap().to_vec1().unwrap();
        let bv: Vec<f32> = b.flatten_all().unwrap().to_vec1().unwrap();
        assert_eq!(av.len(), bv.len(), "tensor length mismatch");
        av.iter()
            .zip(&bv)
            .map(|(x, y)| (x - y).abs())
            .fold(0.0, f32::max)
    }

    fn case(name: &str) -> Value {
        let g = golden();
        let c = g["cases"][name].clone();
        assert!(!c.is_null(), "fixture case {name} present");
        c
    }

    fn router_matches(name: &str) {
        let c = case(name);
        let (n, h, e, k) = (
            usz(&c, "tokens"),
            usz(&c, "hidden"),
            usz(&c, "experts"),
            usz(&c, "top_k"),
        );
        let x = ten(&c, "x", &[n, h]);
        let w = ten(&c, "weight", &[e, h]);
        let (logits, scores, indices) = topk_router(&x, &w, k).unwrap();
        assert!(max_abs_diff(&logits, &ten(&c, "logits", &[n, e])) <= ORACLE_TOL);
        assert!(max_abs_diff(&scores, &ten(&c, "scores", &[n, k])) <= ORACLE_TOL);
        // Fixture non-degeneracy: a regeneration with the shipped ZERO router
        // init would make the probabilities uniform and the exact-index
        // assert below tie-broken (vacuous). Demand a sharp fixture.
        let kf = k as f32;
        assert!(
            vecf(&c["scores"])
                .iter()
                .any(|&v| (v - 1.0 / kf).abs() > 0.05),
            "{name}: degenerate (near-uniform) router fixture"
        );
        // Indices must match the oracle EXACTLY (no ties on random inputs).
        let got: Vec<u32> = indices.flatten_all().unwrap().to_vec1().unwrap();
        assert_eq!(got, veci(&c["indices"]), "{name}: routed experts diverged");
    }

    #[test]
    fn router_matches_the_reference_dump() {
        router_matches("router_t5");
        router_matches("router_t1");
    }

    /// Skipping the unconditional renorm is a real bug the oracle catches —
    /// the gate above is non-vacuous (negative control).
    #[test]
    fn unnormalized_topk_diverges_from_the_oracle() {
        let c = case("router_t5");
        let (n, h, e, k) = (
            usz(&c, "tokens"),
            usz(&c, "hidden"),
            usz(&c, "experts"),
            usz(&c, "top_k"),
        );
        let x = ten(&c, "x", &[n, h]);
        let w = ten(&c, "weight", &[e, h]);
        let logits = x.matmul(&w.t().unwrap()).unwrap();
        let probs = softmax(&logits, D::Minus1).unwrap();
        let order = probs.arg_sort_last_dim(false).unwrap();
        let idx = order.narrow(D::Minus1, 0, k).unwrap().contiguous().unwrap();
        let unnormalized = probs.gather(&idx, D::Minus1).unwrap();
        assert!(
            max_abs_diff(&unnormalized, &ten(&c, "scores", &[n, k])) > 1e-2,
            "the renorm gate would not catch a skipped renormalization"
        );
    }

    fn experts_matches(name: &str) {
        let c = case(name);
        let (n, h, e, k, m) = (
            usz(&c, "tokens"),
            usz(&c, "hidden"),
            usz(&c, "experts"),
            usz(&c, "top_k"),
            usz(&c, "moe_inter"),
        );
        let x = ten(&c, "x", &[n, h]);
        let gate_up = ten(&c, "gate_up_proj", &[e, 2 * m, h]);
        let down = ten(&c, "down_proj", &[e, h, m]);
        let indices = Tensor::from_vec(veci(&c["indices"]), (n, k), &Device::Cpu).expect("indices");
        let scores = ten(&c, "scores", &[n, k]);
        let out = moe_experts(&x, &gate_up, &down, &indices, &scores).unwrap();
        assert!(
            max_abs_diff(&out, &ten(&c, "out", &[n, h])) <= ORACLE_TOL,
            "{name}: expert outputs diverged"
        );
    }

    #[test]
    fn experts_match_the_reference_dump_including_unhit_experts() {
        experts_matches("experts_t9");
        // 2 tokens × top-3 of 8: several experts serve no token — pins the
        // reference's skip-unhit behavior (and that unrouted rows stay 0
        // before the shared expert is added).
        experts_matches("experts_unhit_t2");
    }

    /// Swapping the packed gate/up halves is a real bug the oracle catches
    /// (negative control for the expert gate).
    #[test]
    fn swapped_gate_up_halves_diverge_from_the_oracle() {
        let c = case("experts_t9");
        let (n, h, e, k, m) = (
            usz(&c, "tokens"),
            usz(&c, "hidden"),
            usz(&c, "experts"),
            usz(&c, "top_k"),
            usz(&c, "moe_inter"),
        );
        let x = ten(&c, "x", &[n, h]);
        let gate_up = ten(&c, "gate_up_proj", &[e, 2 * m, h]);
        // Swap the halves along the 2m axis.
        let up_gate = Tensor::cat(
            &[
                gate_up.narrow(1, m, m).unwrap(),
                gate_up.narrow(1, 0, m).unwrap(),
            ],
            1,
        )
        .unwrap();
        let down = ten(&c, "down_proj", &[e, h, m]);
        let indices = Tensor::from_vec(veci(&c["indices"]), (n, k), &Device::Cpu).expect("indices");
        let scores = ten(&c, "scores", &[n, k]);
        let out = moe_experts(&x, &up_gate, &down, &indices, &scores).unwrap();
        assert!(
            max_abs_diff(&out, &ten(&c, "out", &[n, h])) > 1e-2,
            "the expert gate would not catch swapped gate/up halves"
        );
    }

    #[test]
    fn an_out_of_range_routed_index_fails_loud() {
        let dev = Device::Cpu;
        let x = Tensor::randn(0f32, 1.0, (2, 4), &dev).unwrap();
        let gate_up = Tensor::randn(0f32, 1.0, (2, 6, 4), &dev).unwrap();
        let down = Tensor::randn(0f32, 1.0, (2, 4, 3), &dev).unwrap();
        let indices = Tensor::from_vec(vec![0u32, 7], (2, 1), &dev).unwrap();
        let scores = Tensor::from_vec(vec![1f32, 1.0], (2, 1), &dev).unwrap();
        let err = moe_experts(&x, &gate_up, &down, &indices, &scores).unwrap_err();
        assert!(err.to_string().contains("routed index"));
    }

    fn block_weights<'a>(
        c: &Value,
        store: &'a mut Vec<Tensor>,
        dims: &BlockDims,
    ) -> SparseMoeWeights<'a> {
        store.clear();
        store.push(ten(c, "router_weight", &[dims.e, dims.h]));
        store.push(ten(c, "gate_up_proj", &[dims.e, 2 * dims.m, dims.h]));
        store.push(ten(c, "down_proj", &[dims.e, dims.h, dims.m]));
        store.push(ten(c, "shared_gate_proj", &[dims.si, dims.h]));
        store.push(ten(c, "shared_up_proj", &[dims.si, dims.h]));
        store.push(ten(c, "shared_down_proj", &[dims.h, dims.si]));
        store.push(ten(c, "shared_expert_gate", &[1, dims.h]));
        SparseMoeWeights {
            router: &store[0],
            gate_up: &store[1],
            down: &store[2],
            shared_gate: &store[3],
            shared_up: &store[4],
            shared_down: &store[5],
            shared_expert_gate: &store[6],
        }
    }

    struct BlockDims {
        e: usize,
        h: usize,
        m: usize,
        si: usize,
    }

    fn block_dims(c: &Value) -> BlockDims {
        BlockDims {
            e: usz(c, "experts"),
            h: usz(c, "hidden"),
            m: usz(c, "moe_inter"),
            si: usz(c, "shared_inter"),
        }
    }

    fn block_matches(name: &str) {
        let c = case(name);
        let (b, t) = (usz(&c, "b"), usz(&c, "t"));
        let k = usz(&c, "top_k");
        let dims = block_dims(&c);
        let x = ten(&c, "x", &[b, t, dims.h]);
        let mut store = Vec::new();
        let weights = block_weights(&c, &mut store, &dims);
        let out = sparse_moe_block(&x, &weights, k).unwrap();
        assert!(
            max_abs_diff(&out, &ten(&c, "out", &[b, t, dims.h])) <= ORACLE_TOL,
            "{name}: block output diverged"
        );
    }

    #[test]
    fn sparse_block_matches_the_reference_dump_across_geometries() {
        block_matches("block_b1_t6");
        block_matches("block_b2_t4");
        // k = 1 + non-divisible widths: the degenerate-renorm edge (a single
        // kept probability renormalizes to exactly 1).
        block_matches("block_k1_b1_t3");
    }

    /// Swapping the shared expert's gate and up weights (shape-symmetric
    /// `[si, h]`) is a real bug the block oracle catches — `SwiGLU` is not
    /// gate/up-symmetric and the generator seeds them independently
    /// (negative control for the shared-expert wiring).
    #[test]
    fn swapped_shared_gate_and_up_diverge_from_the_oracle() {
        let c = case("block_b1_t6");
        let (b, t) = (usz(&c, "b"), usz(&c, "t"));
        let k = usz(&c, "top_k");
        let dims = block_dims(&c);
        let x = ten(&c, "x", &[b, t, dims.h]);
        let mut store = Vec::new();
        let w = block_weights(&c, &mut store, &dims);
        let swapped = SparseMoeWeights {
            shared_gate: w.shared_up,
            shared_up: w.shared_gate,
            ..w
        };
        let out = sparse_moe_block(&x, &swapped, k).unwrap();
        assert!(
            max_abs_diff(&out, &ten(&c, "out", &[b, t, dims.h])) > 1e-2,
            "the block oracle would not catch swapped shared gate/up"
        );
    }

    /// The router's softmax must run in F32 whatever the input dtype (the
    /// reference passes `dtype=torch.float` unconditionally). Pinned at F64
    /// — the one CPU-supported dtype where "softmax in the input dtype" is
    /// observably different: the genuine kernel's scores equal an F32
    /// softmax of the same F64 logits EXACTLY (identical rounding), while a
    /// softmax computed in F64 diverges at f32-epsilon scale. (bf16 — the
    /// GPU training dtype — has no CPU matmul in candle; that direction
    /// rides the GPU bundle.)
    #[test]
    fn router_softmax_runs_in_f32_for_any_input_dtype() {
        let dev = Device::Cpu;
        let x = Tensor::randn(0f64, 1.0, (4, 16), &dev).unwrap();
        let w = Tensor::randn(0f64, 0.7, (8, 16), &dev).unwrap();
        let (logits, scores, indices) = topk_router(&x, &w, 3).unwrap();
        assert_eq!(scores.dtype(), DType::F64);
        let probs = softmax(&logits.to_dtype(DType::F32).unwrap(), D::Minus1).unwrap();
        let reference = probs.gather(&indices, D::Minus1).unwrap();
        let reference = reference
            .broadcast_div(&reference.sum_keepdim(D::Minus1).unwrap())
            .unwrap()
            .to_dtype(DType::F64)
            .unwrap();
        let diff = max_abs_diff(
            &scores.to_dtype(DType::F32).unwrap(),
            &reference.to_dtype(DType::F32).unwrap(),
        );
        assert_eq!(diff, 0.0, "the router softmax did not run in F32");
    }

    /// Every value path is on the tape: a backward through the block reaches
    /// the router weight, BOTH packed expert tensors, and every shared
    /// piece — and the gradients are finite (the grad-coverage convention).
    #[test]
    fn block_gradients_reach_every_weight() {
        let c = case("block_b1_t6");
        let (b, t) = (usz(&c, "b"), usz(&c, "t"));
        let k = usz(&c, "top_k");
        let dims = block_dims(&c);
        let x = ten(&c, "x", &[b, t, dims.h]);
        let vars: Vec<Var> = [
            ten(&c, "router_weight", &[dims.e, dims.h]),
            ten(&c, "gate_up_proj", &[dims.e, 2 * dims.m, dims.h]),
            ten(&c, "down_proj", &[dims.e, dims.h, dims.m]),
            ten(&c, "shared_gate_proj", &[dims.si, dims.h]),
            ten(&c, "shared_up_proj", &[dims.si, dims.h]),
            ten(&c, "shared_down_proj", &[dims.h, dims.si]),
            ten(&c, "shared_expert_gate", &[1, dims.h]),
        ]
        .into_iter()
        .map(|t| Var::from_tensor(&t).unwrap())
        .collect();
        let weights = SparseMoeWeights {
            router: vars[0].as_tensor(),
            gate_up: vars[1].as_tensor(),
            down: vars[2].as_tensor(),
            shared_gate: vars[3].as_tensor(),
            shared_up: vars[4].as_tensor(),
            shared_down: vars[5].as_tensor(),
            shared_expert_gate: vars[6].as_tensor(),
        };
        let out = sparse_moe_block(&x, &weights, k).unwrap();
        let loss = out.sqr().unwrap().sum_all().unwrap();
        let grads = loss.backward().unwrap();
        let cov = grad_coverage(&vars, &grads).unwrap();
        assert!(cov.is_ok(), "{cov:?}");
        assert_eq!(
            cov.nonzero, 7,
            "every MoE weight must carry gradient: {cov:?}"
        );
    }
}
