//! Sandboxed execution of untrusted, model-generated code.
//!
//! The discovery direction scores a candidate artifact by **running it** — for a
//! GPU-kernel task: compile it, check correctness, benchmark it. That artifact is
//! generated by the policy under training and is therefore **untrusted from the
//! first run** (a [key risk](crate) the spec names explicitly): it may try to read
//! credentials, reach the network, fork-bomb, or exhaust memory. This module is
//! the isolation boundary that lets a [`crate::reward::RewardFn`] execute such code
//! without trusting it.
//!
//! ## Division of labor
//!
//! ferrl owns the *policy* (what to isolate, which limits, what to mount) and
//! **integrates a mature runner** for the mechanism — here
//! [Apptainer](https://apptainer.org/) (formerly Singularity), the de-facto
//! unprivileged container runtime on HPC clusters. A run is one
//! `apptainer exec` of a pinned image with:
//!
//! - `--containall` + `--no-home` + `--cleanenv` — private PID/IPC/env
//!   namespaces and a minimal, read-only rootfs with **no host `$HOME`**, so no
//!   ambient credentials or SSH keys are reachable;
//! - `--net --network none` (the default [`NetworkPolicy`]) — no network, removing
//!   the exfiltration channel;
//! - `--nv` only when [`RunSpec::gpu`] is set — GPU passthrough is opt-in;
//! - read-only / read-write [`Bind`]s for exactly the reference harness and a
//!   scratch directory, nothing else;
//! - `--no-privs --drop-caps all` unconditionally removes payload privilege and
//!   Linux capabilities. Direct [`ApptainerSandbox`] runs accept ordinary host
//!   paths only; kernel-sealed verifier descriptors must use the dedicated-UID
//!   [`crate::verifier_executor::VerifierExecutorSandbox`], which transfers them
//!   with `SCM_RIGHTS` and copies them into service-private paths;
//! - in-image `ulimit`s (CPU, address space, processes, file size), beneath a
//!   **host-side wall-clock supervisor** that is the final authority on the time
//!   budget — it owns a fresh process group and kills the complete launch tree if
//!   the run overruns, and cannot be evaded from inside the container;
//! - optional host-supervised total byte caps for writable binds such as `/work`,
//!   so many-small-file fills are bounded as well as single large writes;
//! - an optional post-launch Unix socket accepted only from the spawned process
//!   tree, so a protected verifier can own machine output without exposing a grade
//!   descriptor through launcher, init, shell, or untrusted worker processes;
//! - **bounded output capture** — at most `CAPTURE_CAP` bytes per stream are read
//!   into host memory, so a payload spewing to stdout cannot exhaust the host;
//!   past the cap the writer blocks on a full pipe and the supervisor reaps it.
//!
//! ## Testing split (the same shape as [`crate::cuda_compat`])
//!
//! The *policy* is pure and fully unit-tested on any machine:
//! [`ApptainerSandbox::build_argv`] and the
//! in-image-script builder encode every isolation flag and resource cap. Their tests
//! are **security-invariant regression guards** — they fail if a future edit drops
//! `--cleanenv`, restores payload capabilities, accepts a sealed descriptor on the
//! direct path, or stops capping processes. The host-side wall-clock supervisor is
//! tested against a plain subprocess (no container runtime needed). The proof that
//! Apptainer *actually contains a hostile payload* — a malicious-probe battery —
//! lives behind the off-by-default `gate` feature in `tests/sandbox_gate.rs`, run on
//! a cluster node with an isolated allocation; it is never compiled in CI, just as
//! the GPU tests are not.

use std::io::Read;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, ExitStatus, Stdio};
use std::sync::mpsc::{self, Receiver};
#[cfg(unix)]
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc,
};
use std::thread;
use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};

#[cfg(unix)]
use std::os::unix::{
    fs::PermissionsExt as _,
    net::{UnixListener, UnixStream},
};
#[cfg(target_os = "linux")]
use std::{fs::File, os::fd::AsRawFd as _};

/// How a host path is exposed inside the sandbox.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BindMode {
    /// Mounted read-only — the payload may read but not modify the source.
    ReadOnly,
    /// Mounted read-write — the payload may write (e.g. a scratch / output dir).
    ReadWrite,
}

impl BindMode {
    /// The `apptainer --bind` mode suffix (`ro` / `rw`).
    fn flag(self) -> &'static str {
        match self {
            BindMode::ReadOnly => "ro",
            BindMode::ReadWrite => "rw",
        }
    }
}

/// A host directory or file bound into the sandbox at a fixed mount point.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Bind {
    /// Host path to expose.
    pub src: PathBuf,
    /// Mount point inside the sandbox.
    pub dst: PathBuf,
    /// Read-only or read-write.
    pub mode: BindMode,
    /// Optional total byte cap for a writable host path, enforced by the host
    /// supervisor over the whole tree.
    pub total_limit: Option<u64>,
}

impl Bind {
    /// A read-only bind of `src` at `dst` — the default for inputs the payload
    /// must not tamper with (the reference harness, fixtures).
    #[must_use]
    pub fn ro(src: impl Into<PathBuf>, dst: impl Into<PathBuf>) -> Self {
        Self {
            src: src.into(),
            dst: dst.into(),
            mode: BindMode::ReadOnly,
            total_limit: None,
        }
    }

    /// A read-write bind of `src` at `dst` — for the single scratch directory the
    /// payload writes its outputs to.
    #[must_use]
    pub fn rw(src: impl Into<PathBuf>, dst: impl Into<PathBuf>) -> Self {
        Self {
            src: src.into(),
            dst: dst.into(),
            mode: BindMode::ReadWrite,
            total_limit: None,
        }
    }

    /// Add a host-supervised total byte cap to this bind.
    #[must_use]
    pub fn with_total_limit(mut self, bytes: u64) -> Self {
        self.total_limit = Some(bytes);
        self
    }

    /// Render as the `src:dst:mode` string `apptainer --bind` expects.
    fn render(&self) -> String {
        format!(
            "{}:{}:{}",
            self.src.display(),
            self.dst.display(),
            self.mode.flag()
        )
    }
}

/// Whether the sandbox is given a network.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum NetworkPolicy {
    /// No network: a private network namespace with no interfaces
    /// (`--net --network none`). The default — generated code has no reason to
    /// reach the network, and denying it removes the exfiltration channel.
    #[default]
    None,
    /// Share the host network namespace (Apptainer's own default). Opt-in only,
    /// for a trusted payload that genuinely needs the network.
    Host,
}

/// Resource ceilings for a sandboxed run.
///
/// `wall` is always enforced (by the host-side wall-clock supervisor). The
/// remaining caps are optional in-image `ulimit`s; leave one `None` to omit it —
/// notably `address_space`, which must usually be `None` for CUDA/GPU payloads,
/// because the CUDA runtime reserves tens of gigabytes of *virtual* address space
/// that an address-space cap would wrongly kill.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResourceLimits {
    /// Wall-clock budget; the host supervisor kills the run when it elapses.
    pub wall: Duration,
    /// CPU-seconds cap (`ulimit -t`), or `None` to omit.
    pub cpu: Option<Duration>,
    /// Address-space cap in bytes (`ulimit -v`), or `None` to omit. Keep `None`
    /// for GPU payloads (see the type docs).
    pub address_space: Option<u64>,
    /// Max processes for the run's uid (`ulimit -u`) — the fork-bomb cap — or `None`.
    pub max_procs: Option<u64>,
    /// Max size a single write may create, in bytes (`ulimit -f`), or `None`.
    pub max_file: Option<u64>,
}

/// A one-launch machine-grade channel connected only after the protected verifier
/// is running inside the sandbox.
///
/// The host listener is created before launch. The verifier connects through the
/// sandbox-visible pathname; the supervisor accepts only a peer whose kernel PID is
/// a descendant of the process it spawned. Launcher, init, and shell processes never
/// inherit the accepted stream, and the verifier must keep it close-on-exec before
/// starting untrusted workers. Both paths must be normalized absolute paths to the
/// same non-empty relative file beneath exactly one read-write [`Bind`]; launch
/// preflight rejects missing, ambiguous, or mismatched mappings.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProtectedOutput {
    /// Unix-socket pathname in the host scratch tree.
    pub host_socket: PathBuf,
    /// The same relative socket as addressed inside the sandbox's matching
    /// read-write bind.
    pub sandbox_socket: PathBuf,
}

impl ProtectedOutput {
    /// Describe the host and sandbox views of one protected output socket. The
    /// corresponding [`RunSpec`] is validated before the listener is created.
    #[must_use]
    pub fn new(host_socket: impl Into<PathBuf>, sandbox_socket: impl Into<PathBuf>) -> Self {
        Self {
            host_socket: host_socket.into(),
            sandbox_socket: sandbox_socket.into(),
        }
    }
}

impl Default for ResourceLimits {
    fn default() -> Self {
        Self {
            wall: Duration::from_secs(120),
            cpu: Some(Duration::from_secs(120)),
            // Omitted by default: an address-space cap is hostile to CUDA, which
            // reserves a huge virtual range. GPU-free callers may set it.
            address_space: None,
            max_procs: Some(256),
            max_file: Some(1 << 30),
        }
    }
}

/// A fully-specified sandboxed run: which image, which command, what is mounted,
/// and the isolation / resource policy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RunSpec {
    /// The container image — an Apptainer `.sif`, or any reference `apptainer
    /// exec` accepts. Descriptor-backed images are accepted only by the protected
    /// verifier executor.
    pub image: PathBuf,
    /// The command + args to run *inside* the sandbox (e.g. `["python",
    /// "/work/eval.py"]`). This is **ferrl-controlled**; untrusted model code is
    /// delivered as a *file* under a [`Bind`], never spliced into this argv.
    pub command: Vec<String>,
    /// Host directories / files exposed inside, with their modes. Descriptor-backed
    /// read-only sources are accepted only by the protected verifier executor.
    pub binds: Vec<Bind>,
    /// Working directory inside the sandbox (`--pwd`).
    pub workdir: PathBuf,
    /// Environment variables to set inside. Combined with `--cleanenv` these are
    /// the *only* variables present — the host environment (and any credentials
    /// in it) never leaks in.
    pub env: Vec<(String, String)>,
    /// Expose the host GPUs (`--nv`). Off by default.
    pub gpu: bool,
    /// Network policy (default: no network).
    pub network: NetworkPolicy,
    /// Resource ceilings.
    pub limits: ResourceLimits,
    /// Optional verifier-only machine-grade channel. Ordinary stdout remains
    /// untrusted diagnostics when this is present.
    pub protected_output: Option<ProtectedOutput>,
}

impl RunSpec {
    /// A minimal spec: run `command` in `image` from `/` with default limits — no
    /// GPU, no network, nothing bound. The `with_*` setters refine it.
    #[must_use]
    pub fn new(image: impl Into<PathBuf>, command: Vec<String>) -> Self {
        Self {
            image: image.into(),
            command,
            binds: Vec::new(),
            workdir: PathBuf::from("/"),
            env: Vec::new(),
            gpu: false,
            network: NetworkPolicy::None,
            limits: ResourceLimits::default(),
            protected_output: None,
        }
    }

    /// Replace the bind set.
    #[must_use]
    pub fn with_binds(mut self, binds: Vec<Bind>) -> Self {
        self.binds = binds;
        self
    }

    /// Set the in-sandbox working directory.
    #[must_use]
    pub fn with_workdir(mut self, workdir: impl Into<PathBuf>) -> Self {
        self.workdir = workdir.into();
        self
    }

    /// Replace the environment allow-list.
    #[must_use]
    pub fn with_env(mut self, env: Vec<(String, String)>) -> Self {
        self.env = env;
        self
    }

    /// Expose the host GPUs (`--nv`).
    #[must_use]
    pub fn with_gpu(mut self, gpu: bool) -> Self {
        self.gpu = gpu;
        self
    }

    /// Set the resource ceilings.
    #[must_use]
    pub fn with_limits(mut self, limits: ResourceLimits) -> Self {
        self.limits = limits;
        self
    }

    /// Add a verifier-only machine-grade channel.
    #[must_use]
    pub fn with_protected_output(mut self, output: ProtectedOutput) -> Self {
        self.protected_output = Some(output);
        self
    }
}

/// How a sandboxed run ended.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RunStatus {
    /// The command exited on its own with this status code.
    Exited(i32),
    /// The run exceeded its wall-clock budget and was killed.
    TimedOut,
    /// The command was killed by a signal (e.g. an OOM or a file-size cap).
    Signaled(i32),
    /// The run exceeded a host-supervised writable-bind total byte cap and was killed.
    ScratchExceeded,
}

impl RunStatus {
    /// `true` iff the command exited cleanly with code `0`.
    #[must_use]
    pub fn is_success(self) -> bool {
        matches!(self, RunStatus::Exited(0))
    }
}

/// A host path whose total disk usage is capped during a sandboxed run.
#[derive(Debug, Clone)]
struct ScratchLimit {
    /// Host path to monitor.
    path: PathBuf,
    /// Maximum total bytes allowed beneath `path`.
    bytes: u64,
}

/// The result of a sandboxed run: how it ended, plus its captured output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RunOutcome {
    /// How the run ended.
    pub status: RunStatus,
    /// Captured standard output (UTF-8 **lossy** — untrusted output may be binary).
    pub stdout: String,
    /// Captured standard error (UTF-8 lossy).
    pub stderr: String,
    /// Bytes received from the verifier-only protected channel. Untrusted stdout
    /// is never promoted into this field.
    pub protected_output: String,
    /// Wall-clock time the run took.
    pub wall: Duration,
}

/// Error from attempting a sandboxed run.
///
/// After the trusted verifier-entry boundary, a non-zero exit, timeout, or OOM is
/// a normal [`RunOutcome`] a reward interprets. The same termination before entry
/// is an infrastructure error because no candidate result was produced.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum SandboxError {
    /// Host paths or launch configuration violate sandbox preflight.
    #[error("invalid sandbox run specification: {0}")]
    InvalidSpec(String),
    /// The sandbox process could not be spawned (e.g. `apptainer` not on `PATH`).
    #[error("failed to spawn sandbox process: {0}")]
    Spawn(#[source] std::io::Error),
    /// An OS error occurred while supervising the run.
    #[error("sandbox supervision failed: {0}")]
    Supervise(#[source] std::io::Error),
    /// The wrapper or container runtime failed before the trusted in-container
    /// verifier command was entered. This is an infrastructure failure, never a
    /// low-quality candidate result.
    #[error("sandbox infrastructure failed before verifier entry ({status:?}): {stderr}")]
    Infrastructure {
        /// How the pre-entry wrapper terminated.
        status: RunStatus,
        /// Bounded wrapper/runtime diagnostics with the entry token removed.
        stderr: String,
    },
    /// A protected verifier executor rejected or could not complete the request.
    #[error("protected verifier executor failed: {0}")]
    Executor(String),
}

/// A backend that runs a [`RunSpec`] under isolation and returns its [`RunOutcome`].
///
/// Production verifier rewards use
/// [`crate::verifier_executor::VerifierExecutorSandbox`]; direct path-backed tools
/// may use [`ApptainerSandbox`]. The trait keeps reward policy separate from either
/// launch mechanism.
pub trait Sandbox {
    /// Run `spec` to completion, or until its wall-clock budget elapses.
    ///
    /// # Errors
    ///
    /// Returns [`SandboxError`] if the run could not reach the trusted verifier
    /// entry boundary. After entry, non-zero exits, timeouts, and resource kills
    /// are reported as [`RunOutcome`]s.
    fn run(&self, spec: &RunSpec) -> Result<RunOutcome, SandboxError>;
}

/// Runs untrusted code under [Apptainer](https://apptainer.org/).
///
/// Construct with [`Default`] (the `apptainer` on `PATH`, a `/bin/bash` in-image
/// shell) or [`ApptainerSandbox::with_bin`] for an explicit path.
#[derive(Debug, Clone)]
pub struct ApptainerSandbox {
    /// The `apptainer` executable — a name on `PATH` or an absolute path.
    bin: PathBuf,
    /// In-image shell used to apply `ulimit`s before `exec`-ing the command.
    shell: PathBuf,
}

impl Default for ApptainerSandbox {
    fn default() -> Self {
        Self {
            bin: PathBuf::from("apptainer"),
            shell: PathBuf::from("/bin/bash"),
        }
    }
}

impl ApptainerSandbox {
    /// Construct with an explicit `apptainer` path (otherwise [`Default`]).
    #[must_use]
    pub fn with_bin(bin: impl Into<PathBuf>) -> Self {
        Self {
            bin: bin.into(),
            ..Self::default()
        }
    }

    /// Build the full `apptainer exec` argument vector for `spec`.
    ///
    /// Pure, so the isolation policy it encodes is unit-testable without running
    /// anything — the `argv_*` tests assert every isolation flag is present.
    #[must_use]
    pub fn build_argv(&self, spec: &RunSpec) -> Vec<String> {
        let mut argv: Vec<String> = vec!["exec".into()];
        // Strong isolation: private PID/IPC/env namespaces + a minimal, read-only
        // rootfs, and crucially no host `$HOME` — so credentials and keys cannot
        // be read. These three are unconditional.
        argv.push("--containall".into());
        argv.push("--no-home".into());
        argv.push("--cleanenv".into());
        argv.push("--no-privs".into());
        argv.push("--drop-caps".into());
        argv.push("all".into());
        if spec.gpu {
            argv.push("--nv".into());
        }
        if matches!(spec.network, NetworkPolicy::None) {
            argv.push("--net".into());
            argv.push("--network".into());
            argv.push("none".into());
        }
        argv.push("--pwd".into());
        argv.push(spec.workdir.display().to_string());
        for bind in &spec.binds {
            argv.push("--bind".into());
            argv.push(bind.render());
        }
        for (key, value) in &spec.env {
            argv.push("--env".into());
            argv.push(format!("{key}={value}"));
        }
        argv.push(spec.image.display().to_string());
        // Inside the image: apply the ulimits, then exec the command directly. The
        // wall-clock budget is owned by the host-side supervisor (outside the
        // container, so the payload cannot evade it) — no in-image timeout.
        argv.push(self.shell.display().to_string());
        argv.push("-c".into());
        argv.push(in_container_script(spec));
        argv
    }

    /// Build the direct path-backed host command.
    fn build_host_command(&self, spec: &RunSpec) -> Command {
        let mut command = Command::new(&self.bin);
        command.args(self.build_argv(spec));
        command
    }
}

impl Sandbox for ApptainerSandbox {
    fn run(&self, spec: &RunSpec) -> Result<RunOutcome, SandboxError> {
        validate_direct_apptainer_spec(spec)?;
        validate_protected_output_mapping(spec)?;
        let protected = ProtectedOutputListener::bind(spec.protected_output.as_ref())?;
        let command = self.build_host_command(spec);
        let scratch_limits = scratch_limits(spec);
        supervise_with_protected_output(
            command,
            spec.limits.wall,
            &scratch_limits,
            EntryProtocol::Required,
            protected,
        )
    }
}

pub(crate) fn is_owned_descriptor_path(path: &Path) -> bool {
    let Some(path) = path.to_str() else {
        return false;
    };
    let prefix = format!("/proc/{}/fd/", std::process::id());
    path.strip_prefix(&prefix)
        .and_then(|value| value.parse::<u32>().ok())
        .is_some_and(|fd| fd > 2)
}

fn validate_direct_apptainer_spec(spec: &RunSpec) -> Result<(), SandboxError> {
    let descriptor = std::iter::once(("sandbox image", spec.image.as_path())).chain(
        spec.binds
            .iter()
            .map(|bind| ("bind source", bind.src.as_path())),
    );
    if let Some((label, path)) = descriptor
        .into_iter()
        .find(|(_, path)| is_owned_descriptor_path(path))
    {
        return Err(SandboxError::InvalidSpec(format!(
            "{label} {} is descriptor-backed; sealed verifier assets require VerifierExecutorSandbox",
            path.display()
        )));
    }
    Ok(())
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ProtectedOutputMapping {
    pub(crate) bind_index: usize,
    pub(crate) relative_path: PathBuf,
}

pub(crate) fn validate_protected_output_mapping(
    spec: &RunSpec,
) -> Result<Option<ProtectedOutputMapping>, SandboxError> {
    let Some(output) = &spec.protected_output else {
        return Ok(None);
    };
    for (label, path) in [
        ("protected output host socket", output.host_socket.as_path()),
        (
            "protected output sandbox socket",
            output.sandbox_socket.as_path(),
        ),
    ] {
        if !is_normal_absolute(path) {
            return Err(SandboxError::InvalidSpec(format!(
                "{label} must be an absolute path without '.' or '..': {}",
                path.display()
            )));
        }
    }

    let mut matches = spec
        .binds
        .iter()
        .enumerate()
        .filter(|(_, bind)| bind.mode == BindMode::ReadWrite)
        .filter_map(|(index, bind)| {
            if !is_normal_absolute(&bind.src) || !is_normal_absolute(&bind.dst) {
                return None;
            }
            let host_relative = output.host_socket.strip_prefix(&bind.src).ok()?;
            let sandbox_relative = output.sandbox_socket.strip_prefix(&bind.dst).ok()?;
            (host_relative == sandbox_relative).then(|| ProtectedOutputMapping {
                bind_index: index,
                relative_path: host_relative.to_path_buf(),
            })
        });
    let mapping = matches.next().ok_or_else(|| {
        SandboxError::InvalidSpec(
            "protected output socket does not map through a read-write bind".to_string(),
        )
    })?;
    if matches.next().is_some() {
        return Err(SandboxError::InvalidSpec(
            "protected output socket maps through more than one read-write bind".to_string(),
        ));
    }
    if mapping.relative_path.as_os_str().is_empty() {
        return Err(SandboxError::InvalidSpec(
            "protected output socket must name a file beneath its read-write bind".to_string(),
        ));
    }
    Ok(Some(mapping))
}

fn is_normal_absolute(path: &Path) -> bool {
    path.is_absolute()
        && path.components().all(|component| {
            matches!(
                component,
                std::path::Component::RootDir | std::path::Component::Normal(_)
            )
        })
}

#[cfg(unix)]
struct ProtectedOutputListener {
    listener: UnixListener,
    #[cfg(target_os = "linux")]
    _parent: File,
}

#[cfg(unix)]
impl ProtectedOutputListener {
    fn bind(output: Option<&ProtectedOutput>) -> Result<Option<Self>, SandboxError> {
        let Some(output) = output else {
            return Ok(None);
        };
        if !output.host_socket.is_absolute() || !output.sandbox_socket.is_absolute() {
            return Err(SandboxError::InvalidSpec(
                "protected output socket paths must be absolute".to_string(),
            ));
        }
        if output.host_socket.exists() {
            return Err(SandboxError::InvalidSpec(format!(
                "protected output socket already exists: {}",
                output.host_socket.display()
            )));
        }
        #[cfg(target_os = "linux")]
        let (listener, parent) = bind_protected_listener(&output.host_socket)?;
        #[cfg(all(unix, not(target_os = "linux")))]
        let listener = UnixListener::bind(&output.host_socket).map_err(SandboxError::Supervise)?;
        std::fs::set_permissions(&output.host_socket, std::fs::Permissions::from_mode(0o600))
            .map_err(SandboxError::Supervise)?;
        listener
            .set_nonblocking(true)
            .map_err(SandboxError::Supervise)?;
        Ok(Some(Self {
            listener,
            #[cfg(target_os = "linux")]
            _parent: parent,
        }))
    }
}

/// Bind through an open parent-directory descriptor so `sockaddr_un::sun_path`
/// never receives an arbitrarily long configured scratch path. The socket is still
/// created at `path`, while the retained directory keeps that descriptor path valid
/// for the listener lifetime.
#[cfg(target_os = "linux")]
fn bind_protected_listener(path: &Path) -> Result<(UnixListener, File), SandboxError> {
    let parent_path = path.parent().ok_or_else(|| {
        SandboxError::InvalidSpec("protected output socket has no parent directory".to_string())
    })?;
    let name = path.file_name().ok_or_else(|| {
        SandboxError::InvalidSpec("protected output socket has no file name".to_string())
    })?;
    let parent = File::open(parent_path).map_err(SandboxError::Supervise)?;
    let descriptor_path = PathBuf::from("/proc/self/fd")
        .join(parent.as_raw_fd().to_string())
        .join(name);
    let listener = UnixListener::bind(descriptor_path).map_err(SandboxError::Supervise)?;
    Ok((listener, parent))
}

#[cfg(not(unix))]
struct ProtectedOutputListener;

#[cfg(not(unix))]
impl ProtectedOutputListener {
    fn bind(output: Option<&ProtectedOutput>) -> Result<Option<Self>, SandboxError> {
        if output.is_some() {
            return Err(SandboxError::InvalidSpec(
                "protected output sockets require Unix".to_string(),
            ));
        }
        Ok(None)
    }
}

/// Extract writable bind limits from the run spec.
fn scratch_limits(spec: &RunSpec) -> Vec<ScratchLimit> {
    spec.binds
        .iter()
        .filter_map(|bind| {
            (bind.mode == BindMode::ReadWrite)
                .then_some(bind.total_limit)
                .flatten()
                .map(|bytes| ScratchLimit {
                    path: bind.src.clone(),
                    bytes,
                })
        })
        .collect()
}

/// The `bash -c` script run *inside* the image: apply the requested `ulimit`s, then
/// `exec` the command. Each `ulimit` is `|| true` so a shell lacking one option does
/// not abort an otherwise-benign run; the malicious-probe gate verifies the caps that
/// matter are actually enforced. The wall-clock budget is **not** enforced here — the
/// host-side supervisor owns it, so an in-container process cannot evade it.
fn in_container_script(spec: &RunSpec) -> String {
    let limits = &spec.limits;
    let mut script = String::new();
    if let Some(cpu) = limits.cpu {
        script.push_str(&format!("ulimit -t {} || true; ", cpu.as_secs().max(1)));
    }
    if let Some(bytes) = limits.address_space {
        script.push_str(&format!("ulimit -v {} || true; ", bytes / 1024));
    }
    if let Some(procs) = limits.max_procs {
        script.push_str(&format!("ulimit -u {procs} || true; "));
    }
    if let Some(bytes) = limits.max_file {
        script.push_str(&format!("ulimit -f {} || true; ", bytes / 1024));
    }
    let quoted: Vec<String> = spec.command.iter().map(|word| shell_quote(word)).collect();
    script.push_str(&format!(
        "printf '%s\\n' '{}' >&2; exec {}",
        SANDBOX_ENTRY_MARKER,
        quoted.join(" ")
    ));
    script
}

/// Written by the trusted in-image shell immediately before it execs the
/// verifier command. Its absence proves that a launcher/runtime failure occurred
/// before candidate evaluation began.
const SANDBOX_ENTRY_MARKER: &str = "ferrl-sandbox-verifier-entry-v1";

/// POSIX single-quote `word` so it is one literal shell word (a literal single
/// quote becomes `'\''`). The command is ferrl-controlled, but quoting keeps paths
/// with spaces correct and forecloses any accidental word-splitting.
fn shell_quote(word: &str) -> String {
    let escaped = word.replace('\'', r"'\''");
    format!("'{escaped}'")
}

/// Poll cadence for the supervisor's wait loop.
const POLL_INTERVAL: Duration = Duration::from_millis(50);

/// After the child is reaped, the longest the supervisor waits for an output drain
/// to finish. A clean exit closes the pipe and the drain arrives at once; this only
/// bounds the *abnormal* case where a killed process left a descendant holding the
/// pipe open, so the supervisor returns promptly instead of blocking on it.
const DRAIN_GRACE: Duration = Duration::from_secs(2);

/// Largest captured stream kept per pipe (1 MiB). Untrusted output is otherwise
/// unbounded — a payload spewing to stdout could exhaust host memory well within the
/// wall budget — so each drain stops reading here and drops the pipe, leaving the
/// writer to block on a full pipe (then be reaped by the wall-clock supervisor). The
/// eval's machine-read *result* travels via the verifier-only protected channel,
/// not this log stream.
pub(crate) const CAPTURE_CAP: usize = 1 << 20;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum EntryProtocol {
    #[cfg(test)]
    NotRequired,
    Required,
}

#[cfg(unix)]
struct ProtectedDrain {
    receiver: Option<Receiver<Vec<u8>>>,
    stop: Option<Arc<AtomicBool>>,
}

#[cfg(unix)]
impl ProtectedDrain {
    fn start(listener: Option<ProtectedOutputListener>, root_pid: u32, deadline: Duration) -> Self {
        let (sender, receiver) = mpsc::channel();
        let Some(listener) = listener else {
            let _ = sender.send(Vec::new());
            return Self {
                receiver: Some(receiver),
                stop: None,
            };
        };
        let stop = Arc::new(AtomicBool::new(false));
        let thread_stop = Arc::clone(&stop);
        thread::spawn(move || {
            let bytes =
                receive_protected_output(&listener.listener, root_pid, deadline, &thread_stop);
            let _ = sender.send(bytes);
        });
        Self {
            receiver: Some(receiver),
            stop: Some(stop),
        }
    }

    fn finish(mut self) -> String {
        let output = self
            .receiver
            .take()
            .map_or_else(String::new, |receiver| collect_output(&receiver));
        if let Some(stop) = &self.stop {
            stop.store(true, Ordering::Release);
        }
        output
    }
}

#[cfg(unix)]
impl Drop for ProtectedDrain {
    fn drop(&mut self) {
        if let Some(stop) = &self.stop {
            stop.store(true, Ordering::Release);
        }
    }
}

#[cfg(unix)]
fn receive_protected_output(
    listener: &UnixListener,
    root_pid: u32,
    deadline: Duration,
    stop: &AtomicBool,
) -> Vec<u8> {
    let started = Instant::now();
    while !stop.load(Ordering::Acquire) && started.elapsed() < deadline {
        match listener.accept() {
            Ok((stream, _)) => {
                if protected_peer_pid(&stream)
                    .is_some_and(|pid| process_descends_from(pid, root_pid))
                {
                    return read_protected_stream(stream, stop);
                }
            }
            Err(error) if error.kind() == std::io::ErrorKind::WouldBlock => {
                thread::sleep(Duration::from_millis(10));
            }
            Err(_) => return Vec::new(),
        }
    }
    Vec::new()
}

#[cfg(target_os = "linux")]
fn protected_peer_pid(stream: &UnixStream) -> Option<u32> {
    let raw_pid = rustix::net::sockopt::socket_peercred(stream)
        .ok()?
        .pid
        .as_raw_pid();
    u32::try_from(raw_pid).ok()
}

#[cfg(all(unix, not(target_os = "linux")))]
fn protected_peer_pid(_stream: &UnixStream) -> Option<u32> {
    None
}

#[cfg(unix)]
fn read_protected_stream(mut stream: UnixStream, stop: &AtomicBool) -> Vec<u8> {
    let _ = stream.set_read_timeout(Some(Duration::from_millis(50)));
    let mut bytes = Vec::new();
    let mut chunk = [0_u8; 8192];
    while bytes.len() < CAPTURE_CAP && !stop.load(Ordering::Acquire) {
        match stream.read(&mut chunk) {
            Ok(0) => break,
            Ok(read) => bytes.extend_from_slice(&chunk[..read.min(CAPTURE_CAP - bytes.len())]),
            Err(error)
                if matches!(
                    error.kind(),
                    std::io::ErrorKind::WouldBlock
                        | std::io::ErrorKind::TimedOut
                        | std::io::ErrorKind::Interrupted
                ) => {}
            Err(_) => break,
        }
    }
    bytes
}

#[cfg(unix)]
fn process_descends_from(mut pid: u32, root_pid: u32) -> bool {
    for _ in 0..256 {
        if pid == root_pid {
            return true;
        }
        let Ok(status) = std::fs::read_to_string(format!("/proc/{pid}/status")) else {
            return false;
        };
        let Some(parent) = status
            .lines()
            .find_map(|line| line.strip_prefix("PPid:\t"))
            .and_then(|value| value.trim().parse::<u32>().ok())
        else {
            return false;
        };
        if parent == 0 || parent == pid {
            return false;
        }
        pid = parent;
    }
    false
}

#[cfg(not(unix))]
struct ProtectedDrain;

#[cfg(not(unix))]
impl ProtectedDrain {
    fn start(
        _listener: Option<ProtectedOutputListener>,
        _root_pid: u32,
        _deadline: Duration,
    ) -> Self {
        Self
    }

    fn finish(self) -> String {
        String::new()
    }
}

/// Spawn `command`, drain its stdout/stderr concurrently, and enforce `deadline`
/// (wall-clock) by killing the process if it overruns. The concurrent drain avoids
/// the classic pipe-buffer deadlock; the kill is the final authority over a runaway.
#[cfg(test)]
fn supervise(
    command: Command,
    deadline: Duration,
    scratch_limits: &[ScratchLimit],
    entry_protocol: EntryProtocol,
) -> Result<RunOutcome, SandboxError> {
    supervise_with_post_spawn_hook_and_protected_output(
        command,
        deadline,
        scratch_limits,
        entry_protocol,
        None,
        |_| Ok(()),
    )
}

fn supervise_with_protected_output(
    command: Command,
    deadline: Duration,
    scratch_limits: &[ScratchLimit],
    entry_protocol: EntryProtocol,
    protected_output: Option<ProtectedOutputListener>,
) -> Result<RunOutcome, SandboxError> {
    supervise_with_post_spawn_hook_and_protected_output(
        command,
        deadline,
        scratch_limits,
        entry_protocol,
        protected_output,
        |_| Ok(()),
    )
}

#[cfg(test)]
fn supervise_with_post_spawn_hook(
    command: Command,
    deadline: Duration,
    scratch_limits: &[ScratchLimit],
    entry_protocol: EntryProtocol,
    post_spawn: impl FnOnce(u32) -> std::io::Result<()>,
) -> Result<RunOutcome, SandboxError> {
    supervise_with_post_spawn_hook_and_protected_output(
        command,
        deadline,
        scratch_limits,
        entry_protocol,
        None,
        post_spawn,
    )
}

fn supervise_with_post_spawn_hook_and_protected_output(
    mut command: Command,
    deadline: Duration,
    scratch_limits: &[ScratchLimit],
    entry_protocol: EntryProtocol,
    protected_output: Option<ProtectedOutputListener>,
    post_spawn: impl FnOnce(u32) -> std::io::Result<()>,
) -> Result<RunOutcome, SandboxError> {
    command
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    configure_process_tree(&mut command);
    let start = Instant::now();
    let child = command.spawn().map_err(SandboxError::Spawn)?;
    let mut child = ProcessTreeGuard::new(child);
    post_spawn(child.id()).map_err(SandboxError::Supervise)?;
    let out = drain(child.child_mut().stdout.take());
    let err = drain(child.child_mut().stderr.take());
    let protected = ProtectedDrain::start(protected_output, child.id(), deadline);

    let mut timed_out = false;
    let mut scratch_exceeded = false;
    let status = loop {
        if let Some(status) = child
            .child_mut()
            .try_wait()
            .map_err(SandboxError::Supervise)?
        {
            scratch_exceeded = scratch_over_limit(scratch_limits);
            // A launcher may exit while a descendant still holds output pipes,
            // descriptors, or its mount namespace. Reap the residual group on
            // every terminal path, not only timeout/scratch enforcement.
            child.terminate_residuals();
            child.disarm();
            break status;
        }
        if start.elapsed() >= deadline {
            timed_out = true;
            break child
                .terminate_and_wait()
                .map_err(SandboxError::Supervise)?;
        }
        if scratch_over_limit(scratch_limits) {
            scratch_exceeded = true;
            break child
                .terminate_and_wait()
                .map_err(SandboxError::Supervise)?;
        }
        thread::sleep(POLL_INTERVAL);
    };

    let status = classify_exit(status, timed_out, scratch_exceeded);
    let stdout = collect_output(&out);
    let mut stderr = collect_output(&err);
    let protected_output = protected.finish();
    if entry_protocol == EntryProtocol::Required && !consume_entry_marker(&mut stderr) {
        return Err(SandboxError::Infrastructure { status, stderr });
    }
    Ok(RunOutcome {
        status,
        stdout,
        stderr,
        protected_output,
        wall: start.elapsed(),
    })
}

/// Armed immediately after spawn. Any subsequent error or unwind kills the
/// complete process group and waits for its leader before stack unwinding can
/// release retained sealed descriptors or the protected verifier channel unsafely.
struct ProcessTreeGuard {
    child: Child,
    armed: bool,
}

impl ProcessTreeGuard {
    fn new(child: Child) -> Self {
        Self { child, armed: true }
    }

    fn id(&self) -> u32 {
        self.child.id()
    }

    fn child_mut(&mut self) -> &mut Child {
        &mut self.child
    }

    fn terminate_residuals(&mut self) {
        terminate_process_tree(&mut self.child);
    }

    fn terminate_and_wait(&mut self) -> std::io::Result<ExitStatus> {
        self.terminate_residuals();
        let status = self.child.wait()?;
        self.armed = false;
        Ok(status)
    }

    fn disarm(&mut self) {
        self.armed = false;
    }
}

impl Drop for ProcessTreeGuard {
    fn drop(&mut self) {
        if self.armed {
            self.terminate_residuals();
            let _ = self.child.wait();
            self.armed = false;
        }
    }
}

/// Give every launch a fresh process group before `exec`. The process group catches
/// launcher/container descendants; Apptainer's unconditional `--containall` PID
/// namespace closes the setsid/session escape path when its namespace init is killed.
#[cfg(unix)]
fn configure_process_tree(command: &mut Command) {
    use std::os::unix::process::CommandExt as _;
    command.process_group(0);
}

#[cfg(not(unix))]
fn configure_process_tree(_command: &mut Command) {}

#[cfg(unix)]
fn terminate_process_tree(child: &mut std::process::Child) {
    if let Ok(raw_pid) = i32::try_from(child.id()) {
        if let Some(pid) = rustix::process::Pid::from_raw(raw_pid) {
            let _ = rustix::process::kill_process_group(pid, rustix::process::Signal::KILL);
        }
    }
    // The direct kill is a race-safe fallback if the child exited or changed
    // process-group state between observation and the group signal.
    let _ = child.kill();
}

#[cfg(not(unix))]
fn terminate_process_tree(child: &mut std::process::Child) {
    let _ = child.kill();
}

fn consume_entry_marker(stderr: &mut String) -> bool {
    let token = format!("{SANDBOX_ENTRY_MARKER}\n");
    let Some(offset) = stderr.find(&token) else {
        return false;
    };
    stderr.replace_range(offset..offset + token.len(), "");
    true
}

/// `true` if any monitored path's current tree size is over its cap. Missing
/// paths count as empty, but other I/O errors fail closed: a payload should not
/// be able to hide scratch usage by changing permissions or racing traversal.
fn scratch_over_limit(limits: &[ScratchLimit]) -> bool {
    limits
        .iter()
        .any(|limit| dir_size(&limit.path).map_or(true, |bytes| bytes > limit.bytes))
}

/// Total bytes used by `path`, summing regular files and directory entries without
/// following symlinks.
fn dir_size(path: &Path) -> std::io::Result<u64> {
    let meta = match std::fs::symlink_metadata(path) {
        Ok(meta) => meta,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(0),
        Err(err) => return Err(err),
    };
    if !meta.is_dir() {
        return Ok(meta.len());
    }
    let mut total = meta.len();
    for entry in std::fs::read_dir(path)? {
        total = total.saturating_add(dir_size(&entry?.path())?);
    }
    Ok(total)
}

/// Read a child pipe on a detached thread, capturing at most [`CAPTURE_CAP`] bytes
/// and sending them back over a channel (a missing pipe yields an immediately-ready
/// empty result). Stopping at the cap drops the read end, so a payload spewing past
/// it blocks on a full pipe and is reaped by the wall-clock supervisor rather than
/// ballooning host memory. The thread is **not** joined: on a clean exit it finishes
/// at EOF; [`collect_output`] takes the bytes with a timeout, so a descendant holding
/// the write end can never block the supervisor.
fn drain<R: Read + Send + 'static>(pipe: Option<R>) -> Receiver<Vec<u8>> {
    let (tx, rx) = mpsc::channel();
    match pipe {
        Some(mut reader) => {
            thread::spawn(move || {
                let mut buf = Vec::new();
                let mut chunk = [0u8; 8192];
                while buf.len() < CAPTURE_CAP {
                    match reader.read(&mut chunk) {
                        Ok(0) => break,
                        Ok(n) => {
                            let room = CAPTURE_CAP - buf.len();
                            buf.extend_from_slice(&chunk[..n.min(room)]);
                        }
                        Err(ref e) if e.kind() == std::io::ErrorKind::Interrupted => {}
                        Err(_) => break,
                    }
                }
                let _ = tx.send(buf);
            });
        }
        None => {
            let _ = tx.send(Vec::new());
        }
    }
    rx
}

/// Take a drain's bytes — UTF-8-**lossily**, since untrusted output may be binary —
/// waiting at most [`DRAIN_GRACE`] so a descendant holding the pipe cannot block the
/// supervisor. A clean exit closes the pipe and the bytes arrive at once.
fn collect_output(rx: &Receiver<Vec<u8>>) -> String {
    let bytes = rx.recv_timeout(DRAIN_GRACE).unwrap_or_default();
    String::from_utf8_lossy(&bytes).into_owned()
}

/// Classify a finished child into a [`RunStatus`].
fn classify_exit(status: ExitStatus, timed_out: bool, scratch_exceeded: bool) -> RunStatus {
    if scratch_exceeded {
        return RunStatus::ScratchExceeded;
    }
    if timed_out {
        return RunStatus::TimedOut;
    }
    match status.code() {
        Some(code) => RunStatus::Exited(code),
        None => RunStatus::Signaled(signal_of(&status)),
    }
}

/// The terminating signal of a child that exited by signal (`-1` if unknown).
#[cfg(unix)]
fn signal_of(status: &ExitStatus) -> i32 {
    use std::os::unix::process::ExitStatusExt;
    status.signal().unwrap_or(-1)
}

/// Non-Unix fallback: signal numbers are not available.
#[cfg(not(unix))]
fn signal_of(_status: &ExitStatus) -> i32 {
    -1
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec() -> RunSpec {
        RunSpec::new("/img.sif", vec!["python".into(), "/work/eval.py".into()])
    }

    /// Position of `needle` in `argv`, or `None` — keeps the assertions
    /// unambiguous about `String`/`&str` comparison.
    fn pos(argv: &[String], needle: &str) -> Option<usize> {
        argv.iter().position(|s| s.as_str() == needle)
    }

    #[test]
    fn argv_always_isolates_env_home_and_namespaces() {
        let argv = ApptainerSandbox::default().build_argv(&spec());
        for flag in [
            "exec",
            "--containall",
            "--no-home",
            "--cleanenv",
            "--no-privs",
            "--drop-caps",
        ] {
            assert!(pos(&argv, flag).is_some(), "argv missing {flag}");
        }
        let drop_caps = pos(&argv, "--drop-caps").unwrap();
        assert_eq!(argv[drop_caps + 1], "all");
    }

    #[test]
    fn argv_denies_network_by_default() {
        let argv = ApptainerSandbox::default().build_argv(&spec());
        assert!(
            argv.windows(3)
                .any(|w| w[0] == "--net" && w[1] == "--network" && w[2] == "none"),
            "default spec must deny the network"
        );
    }

    #[test]
    fn argv_shares_host_network_only_on_opt_in() {
        let argv = ApptainerSandbox::default().build_argv(&RunSpec {
            network: NetworkPolicy::Host,
            ..spec()
        });
        assert!(pos(&argv, "--network").is_none());
        assert!(pos(&argv, "--net").is_none());
    }

    #[test]
    fn argv_exposes_gpu_only_when_requested() {
        let off = ApptainerSandbox::default().build_argv(&spec());
        assert!(pos(&off, "--nv").is_none());
        let on = ApptainerSandbox::default().build_argv(&spec().with_gpu(true));
        assert!(pos(&on, "--nv").is_some());
    }

    #[test]
    fn argv_renders_binds_with_their_modes() {
        let argv = ApptainerSandbox::default().build_argv(&spec().with_binds(vec![
            Bind::ro("/h/ref", "/ref"),
            Bind::rw("/h/scratch", "/work"),
        ]));
        assert!(pos(&argv, "/h/ref:/ref:ro").is_some());
        assert!(pos(&argv, "/h/scratch:/work:rw").is_some());
    }

    #[test]
    fn argv_sets_workdir_and_env_allowlist() {
        let argv = ApptainerSandbox::default().build_argv(
            &spec()
                .with_workdir("/work")
                .with_env(vec![("PYTHONHASHSEED".into(), "0".into())]),
        );
        let pwd = pos(&argv, "--pwd").expect("--pwd present");
        assert_eq!(argv[pwd + 1], "/work");
        let env = pos(&argv, "--env").expect("--env present");
        assert_eq!(argv[env + 1], "PYTHONHASHSEED=0");
    }

    #[test]
    fn argv_ends_with_image_then_shell_command() {
        let sandbox = ApptainerSandbox::default();
        let argv = sandbox.build_argv(&spec());
        // ... <image> /bin/bash -c <script>
        let n = argv.len();
        assert_eq!(argv[n - 4], "/img.sif");
        assert_eq!(argv[n - 3], "/bin/bash");
        assert_eq!(argv[n - 2], "-c");
        assert!(argv[n - 1].contains("exec 'python'"));
    }

    #[test]
    fn ordinary_paths_execute_apptainer_directly() {
        let command = ApptainerSandbox::default().build_host_command(&spec());
        assert_eq!(command.get_program(), "apptainer");
    }

    #[test]
    fn direct_backend_rejects_descriptor_backed_assets() {
        let descriptor = PathBuf::from(format!("/proc/{}/fd/10", std::process::id()));
        let error = validate_direct_apptainer_spec(&RunSpec::new(descriptor, vec!["true".into()]))
            .unwrap_err()
            .to_string();
        assert!(error.contains("require VerifierExecutorSandbox"));
    }

    #[test]
    fn protected_output_requires_exact_read_write_bind_mapping() {
        let valid = spec()
            .with_binds(vec![Bind::rw("/host/scratch", "/work")])
            .with_protected_output(ProtectedOutput::new(
                "/host/scratch/grade.sock",
                "/work/grade.sock",
            ));
        assert_eq!(
            validate_protected_output_mapping(&valid).unwrap(),
            Some(ProtectedOutputMapping {
                bind_index: 0,
                relative_path: PathBuf::from("grade.sock"),
            })
        );

        let mismatched = RunSpec {
            protected_output: Some(ProtectedOutput::new(
                "/host/scratch/grade.sock",
                "/work/other.sock",
            )),
            ..valid.clone()
        };
        assert!(validate_protected_output_mapping(&mismatched).is_err());

        let traversal = RunSpec {
            protected_output: Some(ProtectedOutput::new(
                "/host/scratch/../grade.sock",
                "/work/grade.sock",
            )),
            ..valid
        };
        assert!(validate_protected_output_mapping(&traversal).is_err());
    }

    #[test]
    #[allow(clippy::cognitive_complexity)] // one assertion per encoded resource/entry boundary
    fn in_container_script_encodes_the_ulimits_then_execs() {
        let script = in_container_script(&spec().with_limits(ResourceLimits {
            wall: Duration::from_secs(30),
            cpu: Some(Duration::from_secs(25)),
            address_space: Some(2 << 30),
            max_procs: Some(64),
            max_file: Some(8 << 20),
        }));
        assert!(script.contains("ulimit -t 25"));
        assert!(script.contains("ulimit -v 2097152")); // 2 GiB / 1 KiB
        assert!(script.contains("ulimit -u 64"));
        assert!(script.contains("ulimit -f 8192")); // 8 MiB / 1 KiB
                                                    // No in-image timeout: the host supervisor owns the wall-clock budget.
        assert!(!script.contains("timeout"));
        assert!(script.contains(SANDBOX_ENTRY_MARKER));
        assert!(script.contains("exec 'python' '/work/eval.py'"));
    }

    #[test]
    fn in_container_script_omits_unset_limits() {
        let script = in_container_script(&spec().with_limits(ResourceLimits {
            wall: Duration::from_secs(5),
            cpu: None,
            address_space: None,
            max_procs: None,
            max_file: None,
        }));
        assert!(!script.contains("ulimit"));
        assert_eq!(
            script,
            format!("printf '%s\\n' '{SANDBOX_ENTRY_MARKER}' >&2; exec 'python' '/work/eval.py'")
        );
    }

    #[test]
    fn shell_quote_neutralizes_single_quotes() {
        assert_eq!(shell_quote("a b"), "'a b'");
        assert_eq!(shell_quote("it's"), r"'it'\''s'");
    }

    #[test]
    fn command_words_are_shell_quoted_in_the_script() {
        let script = in_container_script(&RunSpec::new(
            "/img.sif",
            vec!["python".into(), "/work/a b.py".into()],
        ));
        assert!(script.contains("'python' '/work/a b.py'"));
    }

    #[test]
    fn run_status_is_success_only_on_zero_exit() {
        assert!(RunStatus::Exited(0).is_success());
        assert!(!RunStatus::Exited(1).is_success());
        assert!(!RunStatus::TimedOut.is_success());
        assert!(!RunStatus::Signaled(9).is_success());
        assert!(!RunStatus::ScratchExceeded.is_success());
    }

    // --- Host-side supervisor: real subprocess, no container runtime needed. ---

    #[cfg(unix)]
    fn sh(script: &str) -> Command {
        let mut command = Command::new("/bin/sh");
        command.arg("-c").arg(script);
        command
    }

    #[cfg(unix)]
    #[test]
    fn supervise_captures_stdout_on_clean_exit() {
        let outcome = supervise(
            sh("printf hello"),
            Duration::from_secs(5),
            &[],
            EntryProtocol::NotRequired,
        )
        .unwrap();
        assert_eq!(outcome.status, RunStatus::Exited(0));
        assert_eq!(outcome.stdout, "hello");
    }

    #[cfg(unix)]
    #[test]
    fn supervise_captures_stderr_and_nonzero_exit() {
        let outcome = supervise(
            sh("printf oops 1>&2; exit 3"),
            Duration::from_secs(5),
            &[],
            EntryProtocol::NotRequired,
        )
        .unwrap();
        assert_eq!(outcome.status, RunStatus::Exited(3));
        assert_eq!(outcome.stderr, "oops");
    }

    #[cfg(unix)]
    #[test]
    fn supervise_kills_on_wallclock_overrun() {
        // `sh -c 'sleep 30'` exec-replaces sh with sleep, so the kill closes the
        // pipe and the drain returns promptly.
        let outcome = supervise(
            sh("sleep 30"),
            Duration::from_millis(300),
            &[],
            EntryProtocol::NotRequired,
        )
        .unwrap();
        assert_eq!(outcome.status, RunStatus::TimedOut);
        assert!(
            outcome.wall < Duration::from_secs(5),
            "the overrun should have been killed promptly, took {:?}",
            outcome.wall
        );
    }

    #[cfg(unix)]
    #[test]
    fn supervise_reports_a_spawn_failure() {
        let err = supervise(
            Command::new("/no/such/ferrl-binary-xyz"),
            Duration::from_secs(1),
            &[],
            EntryProtocol::NotRequired,
        )
        .unwrap_err();
        assert!(matches!(err, SandboxError::Spawn(_)));
    }

    #[cfg(unix)]
    #[test]
    fn supervise_reports_a_signal_death() {
        // The child kills itself with SIGKILL — it dies by signal (no exit code),
        // so the outcome is `Signaled`, exercising the signal-classification path.
        let outcome = supervise(
            sh("kill -KILL $$"),
            Duration::from_secs(5),
            &[],
            EntryProtocol::NotRequired,
        )
        .unwrap();
        assert!(
            matches!(outcome.status, RunStatus::Signaled(_)),
            "expected a signal death, got {:?}",
            outcome.status
        );
    }

    #[cfg(unix)]
    #[test]
    fn run_supervises_the_built_command() {
        // Point the sandbox at `/bin/true` instead of `apptainer`: `run` still
        // builds the full argv and supervises the process, so the host-side path
        // (`Sandbox::run`) is covered without a container runtime. `/bin/true`
        // ignores the argv and exits 0.
        let error = ApptainerSandbox::with_bin("/bin/true")
            .run(&spec())
            .unwrap_err();
        assert!(matches!(
            error,
            SandboxError::Infrastructure {
                status: RunStatus::Exited(0),
                ..
            }
        ));
    }

    #[cfg(unix)]
    #[test]
    fn verifier_entry_protocol_distinguishes_candidate_and_infrastructure_failures() {
        let entered = format!("printf '%s\\n' '{SANDBOX_ENTRY_MARKER}' >&2; exit 7");
        let outcome = supervise(
            sh(&entered),
            Duration::from_secs(5),
            &[],
            EntryProtocol::Required,
        )
        .unwrap();
        assert_eq!(outcome.status, RunStatus::Exited(7));
        assert_eq!(outcome.stderr, "");

        let error = supervise(
            sh("printf wrapper-failed >&2; exit 7"),
            Duration::from_secs(5),
            &[],
            EntryProtocol::Required,
        )
        .unwrap_err();
        assert!(matches!(
            error,
            SandboxError::Infrastructure {
                status: RunStatus::Exited(7),
                ref stderr,
            } if stderr == "wrapper-failed"
        ));
    }

    #[cfg(unix)]
    #[test]
    fn supervise_kills_the_complete_process_group() {
        let outcome = supervise(
            sh("sleep 30 & printf '%s\\n' \"$!\"; wait"),
            Duration::from_millis(300),
            &[],
            EntryProtocol::NotRequired,
        )
        .unwrap();
        assert_eq!(outcome.status, RunStatus::TimedOut);
        let descendant = outcome.stdout.trim().parse::<u32>().unwrap();
        let proc_path = PathBuf::from(format!("/proc/{descendant}"));
        let wait_started = Instant::now();
        while proc_path.exists() && wait_started.elapsed() < Duration::from_secs(2) {
            thread::sleep(Duration::from_millis(10));
        }
        assert!(
            !proc_path.exists(),
            "descendant {descendant} survived the process-tree kill"
        );
    }

    #[cfg(unix)]
    #[test]
    fn supervise_reaps_descendants_after_the_launcher_exits() {
        let outcome = supervise(
            sh("sleep 30 & printf '%s\\n' \"$!\"; exit 0"),
            Duration::from_secs(5),
            &[],
            EntryProtocol::NotRequired,
        )
        .unwrap();
        assert_eq!(outcome.status, RunStatus::Exited(0));
        let descendant = outcome.stdout.trim().parse::<u32>().unwrap();
        let proc_path = PathBuf::from(format!("/proc/{descendant}"));
        let wait_started = Instant::now();
        while proc_path.exists() && wait_started.elapsed() < Duration::from_secs(2) {
            thread::sleep(Duration::from_millis(10));
        }
        assert!(
            !proc_path.exists(),
            "descendant {descendant} survived its launcher's exit"
        );
    }

    #[cfg(unix)]
    fn wait_for_descendant_pid(path: &Path) -> u32 {
        let started = Instant::now();
        loop {
            if let Ok(value) = std::fs::read_to_string(path) {
                if let Ok(pid) = value.trim().parse() {
                    return pid;
                }
            }
            assert!(
                started.elapsed() < Duration::from_secs(2),
                "child did not publish its descendant pid"
            );
            thread::sleep(Duration::from_millis(10));
        }
    }

    #[cfg(unix)]
    fn assert_process_gone(pid: u32) {
        let proc_path = PathBuf::from(format!("/proc/{pid}"));
        let started = Instant::now();
        while proc_path.exists() && started.elapsed() < Duration::from_secs(2) {
            thread::sleep(Duration::from_millis(10));
        }
        assert!(
            !proc_path.exists(),
            "descendant {pid} survived guard teardown"
        );
    }

    #[cfg(unix)]
    #[test]
    fn post_spawn_supervision_error_drops_through_armed_tree_guard() {
        let root =
            std::env::temp_dir().join(format!("ferrl-post-spawn-error-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        let pid_file = root.join("descendant.pid");
        let script = format!(
            "sleep 30 & printf '%s\\n' \"$!\" > {}; wait",
            shell_quote(&pid_file.display().to_string())
        );
        let error = supervise_with_post_spawn_hook(
            sh(&script),
            Duration::from_secs(5),
            &[],
            EntryProtocol::NotRequired,
            |_| {
                let _ = wait_for_descendant_pid(&pid_file);
                Err(std::io::Error::other(
                    "injected post-spawn supervision error",
                ))
            },
        )
        .unwrap_err();
        assert!(matches!(error, SandboxError::Supervise(_)));
        let descendant = wait_for_descendant_pid(&pid_file);
        assert_process_gone(descendant);
        let _ = std::fs::remove_dir_all(root);
    }

    #[cfg(unix)]
    #[test]
    fn post_spawn_unwind_drops_through_armed_tree_guard() {
        let root =
            std::env::temp_dir().join(format!("ferrl-post-spawn-unwind-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        let pid_file = root.join("descendant.pid");
        let script = format!(
            "sleep 30 & printf '%s\\n' \"$!\" > {}; wait",
            shell_quote(&pid_file.display().to_string())
        );
        let unwind = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            let _ = supervise_with_post_spawn_hook(
                sh(&script),
                Duration::from_secs(5),
                &[],
                EntryProtocol::NotRequired,
                |_| {
                    let _ = wait_for_descendant_pid(&pid_file);
                    panic!("injected post-spawn unwind")
                },
            );
        }));
        assert!(unwind.is_err());
        let descendant = wait_for_descendant_pid(&pid_file);
        assert_process_gone(descendant);
        let _ = std::fs::remove_dir_all(root);
    }

    #[cfg(unix)]
    #[test]
    fn protected_output_accepts_only_the_spawned_tree_and_keeps_stdout_separate() {
        use std::io::Write as _;

        let root = std::env::temp_dir().join(format!(
            "ferrl-protected-output-test-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        let socket = root.join("grade.sock");
        let listener =
            ProtectedOutputListener::bind(Some(&ProtectedOutput::new(&socket, "/work/grade.sock")))
                .unwrap();
        let drain = ProtectedDrain::start(listener, std::process::id(), Duration::from_secs(5));
        let writer = thread::spawn(move || {
            let mut stream = UnixStream::connect(socket).unwrap();
            stream.write_all(b"trusted-grade\n").unwrap();
        });
        writer.join().unwrap();
        assert_eq!(drain.finish(), "trusted-grade\n");
        let _ = std::fs::remove_dir_all(root);
    }

    #[cfg(unix)]
    #[test]
    fn protected_output_rejects_a_peer_outside_the_spawned_tree() {
        use std::io::Write as _;

        let root = std::env::temp_dir().join(format!(
            "ferrl-protected-output-peer-test-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        let socket = root.join("grade.sock");
        let listener =
            ProtectedOutputListener::bind(Some(&ProtectedOutput::new(&socket, "/work/grade.sock")))
                .unwrap();
        let drain = ProtectedDrain::start(listener, u32::MAX, Duration::from_millis(200));
        let mut stream = UnixStream::connect(socket).unwrap();
        stream.write_all(b"forged-grade\n").unwrap();
        drop(stream);
        thread::sleep(Duration::from_millis(250));
        assert_eq!(drain.finish(), "");
        let _ = std::fs::remove_dir_all(root);
    }

    #[cfg(unix)]
    #[test]
    fn supervise_kills_when_scratch_total_exceeds_limit() {
        let dir =
            std::env::temp_dir().join(format!("ferrl-scratch-limit-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let script = format!(
            "dd if=/dev/zero of={}/big bs=1024 count=2048 2>/dev/null; sleep 30",
            shell_quote(&dir.display().to_string())
        );
        let outcome = supervise(
            sh(&script),
            Duration::from_secs(10),
            &[ScratchLimit {
                path: dir.clone(),
                bytes: 1 << 20,
            }],
            EntryProtocol::NotRequired,
        )
        .unwrap();
        let _ = std::fs::remove_dir_all(&dir);
        assert_eq!(outcome.status, RunStatus::ScratchExceeded);
        assert!(
            outcome.wall < Duration::from_secs(5),
            "scratch overflow should kill promptly, took {:?}",
            outcome.wall
        );
    }

    #[cfg(unix)]
    #[test]
    fn supervise_reports_scratch_overflow_even_after_clean_exit() {
        let dir = std::env::temp_dir().join(format!(
            "ferrl-scratch-exit-limit-test-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let script = format!(
            "dd if=/dev/zero of={}/big bs=1024 count=2048 2>/dev/null; exit 0",
            shell_quote(&dir.display().to_string())
        );
        let outcome = supervise(
            sh(&script),
            Duration::from_secs(10),
            &[ScratchLimit {
                path: dir.clone(),
                bytes: 1 << 20,
            }],
            EntryProtocol::NotRequired,
        )
        .unwrap();
        let _ = std::fs::remove_dir_all(&dir);
        assert_eq!(outcome.status, RunStatus::ScratchExceeded);
    }

    #[cfg(unix)]
    #[test]
    fn supervise_bounds_captured_output() {
        // A process spewing far more than the cap is captured only up to CAPTURE_CAP,
        // so untrusted output cannot exhaust host memory; past the cap the read end is
        // dropped and the writer EPIPEs, so the run ends without ballooning the buffer.
        let outcome = supervise(
            sh("head -c 50000000 /dev/zero"),
            Duration::from_secs(5),
            &[],
            EntryProtocol::NotRequired,
        )
        .unwrap();
        assert!(
            outcome.stdout.len() <= CAPTURE_CAP,
            "captured {} bytes, cap is {CAPTURE_CAP}",
            outcome.stdout.len()
        );
    }

    #[test]
    fn drain_of_a_missing_pipe_yields_empty_output() {
        // The `None` arm (a child without a captured pipe) sends an immediately
        // ready empty result, so `collect_output` returns "" without waiting.
        let rx = drain(None::<std::io::Empty>);
        assert_eq!(collect_output(&rx), "");
    }
}
