//! Sandboxed execution of untrusted, model-generated code.
//!
//! The discovery direction scores a candidate artifact by **running it** — for a
//! GPU-kernel task: compile it, check correctness, benchmark it. That artifact is
//! generated by the policy under training and is therefore **untrusted from the
//! first run** (a [key risk](crate) the spec names explicitly): it may try to read
//! credentials, reach the network, fork-bomb, or exhaust memory. This module is
//! the isolation boundary that lets a [`crate::reward::RewardFn`] execute such code
//! without trusting it.
//!
//! ## Division of labor
//!
//! ferrl owns the *policy* (what to isolate, which limits, what to mount) and
//! **integrates a mature runner** for the mechanism — here
//! [Apptainer](https://apptainer.org/) (formerly Singularity), the de-facto
//! unprivileged container runtime on HPC clusters. A run is one
//! `apptainer exec` of a pinned image with:
//!
//! - `--containall` + `--no-home` + `--cleanenv` — private PID/IPC/env
//!   namespaces and a minimal, read-only rootfs with **no host `$HOME`**, so no
//!   ambient credentials or SSH keys are reachable;
//! - `--net --network none` (the default [`NetworkPolicy`]) — no network, removing
//!   the exfiltration channel;
//! - `--nv` only when [`RunSpec::gpu`] is set — GPU passthrough is opt-in;
//! - read-only / read-write [`Bind`]s for exactly the reference harness and a
//!   scratch directory, nothing else;
//! - in-image `ulimit`s (CPU, address space, processes, file size), beneath a
//!   **host-side wall-clock supervisor** that is the final authority on the time
//!   budget — it kills the run if it overruns, and cannot be evaded from inside
//!   the container;
//! - **bounded output capture** — at most `CAPTURE_CAP` bytes per stream are read
//!   into host memory, so a payload spewing to stdout cannot exhaust the host;
//!   past the cap the writer blocks on a full pipe and the supervisor reaps it.
//!
//! ## Testing split (the same shape as [`crate::cuda_compat`])
//!
//! The *policy* is pure and fully unit-tested on any machine: [`ApptainerSandbox::build_argv`]
//! and the in-image-script builder encode every isolation flag and resource cap, and
//! their tests are **security-invariant regression guards** — they fail if a future
//! edit drops `--cleanenv`, opens the network, or stops capping processes. The
//! host-side wall-clock supervisor is tested against a plain subprocess (no
//! container runtime needed). The proof that Apptainer *actually contains a hostile
//! payload* — a malicious-probe battery — lives behind the off-by-default `gate`
//! feature in `tests/sandbox_gate.rs`, run on a cluster node with an isolated
//! allocation; it is never compiled in CI, just as the GPU tests are not.

use std::io::Read;
use std::path::PathBuf;
use std::process::{Command, ExitStatus, Stdio};
use std::sync::mpsc::{self, Receiver};
use std::thread;
use std::time::{Duration, Instant};

/// How a host path is exposed inside the sandbox.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BindMode {
    /// Mounted read-only — the payload may read but not modify the source.
    ReadOnly,
    /// Mounted read-write — the payload may write (e.g. a scratch / output dir).
    ReadWrite,
}

impl BindMode {
    /// The `apptainer --bind` mode suffix (`ro` / `rw`).
    fn flag(self) -> &'static str {
        match self {
            BindMode::ReadOnly => "ro",
            BindMode::ReadWrite => "rw",
        }
    }
}

/// A host directory or file bound into the sandbox at a fixed mount point.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Bind {
    /// Host path to expose.
    pub src: PathBuf,
    /// Mount point inside the sandbox.
    pub dst: PathBuf,
    /// Read-only or read-write.
    pub mode: BindMode,
}

impl Bind {
    /// A read-only bind of `src` at `dst` — the default for inputs the payload
    /// must not tamper with (the reference harness, fixtures).
    #[must_use]
    pub fn ro(src: impl Into<PathBuf>, dst: impl Into<PathBuf>) -> Self {
        Self {
            src: src.into(),
            dst: dst.into(),
            mode: BindMode::ReadOnly,
        }
    }

    /// A read-write bind of `src` at `dst` — for the single scratch directory the
    /// payload writes its outputs to.
    #[must_use]
    pub fn rw(src: impl Into<PathBuf>, dst: impl Into<PathBuf>) -> Self {
        Self {
            src: src.into(),
            dst: dst.into(),
            mode: BindMode::ReadWrite,
        }
    }

    /// Render as the `src:dst:mode` string `apptainer --bind` expects.
    fn render(&self) -> String {
        format!(
            "{}:{}:{}",
            self.src.display(),
            self.dst.display(),
            self.mode.flag()
        )
    }
}

/// Whether the sandbox is given a network.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum NetworkPolicy {
    /// No network: a private network namespace with no interfaces
    /// (`--net --network none`). The default — generated code has no reason to
    /// reach the network, and denying it removes the exfiltration channel.
    #[default]
    None,
    /// Share the host network namespace (Apptainer's own default). Opt-in only,
    /// for a trusted payload that genuinely needs the network.
    Host,
}

/// Resource ceilings for a sandboxed run.
///
/// `wall` is always enforced (by the host-side wall-clock supervisor). The
/// remaining caps are optional in-image `ulimit`s; leave one `None` to omit it —
/// notably `address_space`, which must usually be `None` for CUDA/GPU payloads,
/// because the CUDA runtime reserves tens of gigabytes of *virtual* address space
/// that an address-space cap would wrongly kill.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResourceLimits {
    /// Wall-clock budget; the host supervisor kills the run when it elapses.
    pub wall: Duration,
    /// CPU-seconds cap (`ulimit -t`), or `None` to omit.
    pub cpu: Option<Duration>,
    /// Address-space cap in bytes (`ulimit -v`), or `None` to omit. Keep `None`
    /// for GPU payloads (see the type docs).
    pub address_space: Option<u64>,
    /// Max processes for the run's uid (`ulimit -u`) — the fork-bomb cap — or `None`.
    pub max_procs: Option<u64>,
    /// Max size a single write may create, in bytes (`ulimit -f`), or `None`.
    pub max_file: Option<u64>,
}

impl Default for ResourceLimits {
    fn default() -> Self {
        Self {
            wall: Duration::from_secs(120),
            cpu: Some(Duration::from_secs(120)),
            // Omitted by default: an address-space cap is hostile to CUDA, which
            // reserves a huge virtual range. GPU-free callers may set it.
            address_space: None,
            max_procs: Some(256),
            max_file: Some(1 << 30),
        }
    }
}

/// A fully-specified sandboxed run: which image, which command, what is mounted,
/// and the isolation / resource policy.
#[derive(Debug, Clone)]
pub struct RunSpec {
    /// The container image — an Apptainer `.sif`, or any reference `apptainer
    /// exec` accepts.
    pub image: PathBuf,
    /// The command + args to run *inside* the sandbox (e.g. `["python",
    /// "/work/eval.py"]`). This is **ferrl-controlled**; untrusted model code is
    /// delivered as a *file* under a [`Bind`], never spliced into this argv.
    pub command: Vec<String>,
    /// Host directories / files exposed inside, with their modes.
    pub binds: Vec<Bind>,
    /// Working directory inside the sandbox (`--pwd`).
    pub workdir: PathBuf,
    /// Environment variables to set inside. Combined with `--cleanenv` these are
    /// the *only* variables present — the host environment (and any credentials
    /// in it) never leaks in.
    pub env: Vec<(String, String)>,
    /// Expose the host GPUs (`--nv`). Off by default.
    pub gpu: bool,
    /// Network policy (default: no network).
    pub network: NetworkPolicy,
    /// Resource ceilings.
    pub limits: ResourceLimits,
}

impl RunSpec {
    /// A minimal spec: run `command` in `image` from `/` with default limits — no
    /// GPU, no network, nothing bound. The `with_*` setters refine it.
    #[must_use]
    pub fn new(image: impl Into<PathBuf>, command: Vec<String>) -> Self {
        Self {
            image: image.into(),
            command,
            binds: Vec::new(),
            workdir: PathBuf::from("/"),
            env: Vec::new(),
            gpu: false,
            network: NetworkPolicy::None,
            limits: ResourceLimits::default(),
        }
    }

    /// Replace the bind set.
    #[must_use]
    pub fn with_binds(mut self, binds: Vec<Bind>) -> Self {
        self.binds = binds;
        self
    }

    /// Set the in-sandbox working directory.
    #[must_use]
    pub fn with_workdir(mut self, workdir: impl Into<PathBuf>) -> Self {
        self.workdir = workdir.into();
        self
    }

    /// Replace the environment allow-list.
    #[must_use]
    pub fn with_env(mut self, env: Vec<(String, String)>) -> Self {
        self.env = env;
        self
    }

    /// Expose the host GPUs (`--nv`).
    #[must_use]
    pub fn with_gpu(mut self, gpu: bool) -> Self {
        self.gpu = gpu;
        self
    }

    /// Set the resource ceilings.
    #[must_use]
    pub fn with_limits(mut self, limits: ResourceLimits) -> Self {
        self.limits = limits;
        self
    }
}

/// How a sandboxed run ended.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RunStatus {
    /// The command exited on its own with this status code.
    Exited(i32),
    /// The run exceeded its wall-clock budget and was killed.
    TimedOut,
    /// The command was killed by a signal (e.g. an OOM or a file-size cap).
    Signaled(i32),
}

impl RunStatus {
    /// `true` iff the command exited cleanly with code `0`.
    #[must_use]
    pub fn is_success(self) -> bool {
        matches!(self, RunStatus::Exited(0))
    }
}

/// The result of a sandboxed run: how it ended, plus its captured output.
#[derive(Debug, Clone)]
pub struct RunOutcome {
    /// How the run ended.
    pub status: RunStatus,
    /// Captured standard output (UTF-8 **lossy** — untrusted output may be binary).
    pub stdout: String,
    /// Captured standard error (UTF-8 lossy).
    pub stderr: String,
    /// Wall-clock time the run took.
    pub wall: Duration,
}

/// Error from attempting a sandboxed run.
///
/// A non-zero exit, a timeout, or an OOM is **not** an error — those are normal
/// [`RunOutcome`]s a reward interprets. An error here means the run could not be
/// carried out at all: the sandbox binary could not be spawned, or an OS I/O
/// failure occurred while supervising it.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum SandboxError {
    /// The sandbox process could not be spawned (e.g. `apptainer` not on `PATH`).
    #[error("failed to spawn sandbox process: {0}")]
    Spawn(#[source] std::io::Error),
    /// An OS error occurred while supervising the run.
    #[error("sandbox supervision failed: {0}")]
    Supervise(#[source] std::io::Error),
}

/// A backend that runs a [`RunSpec`] under isolation and returns its [`RunOutcome`].
///
/// The one production implementation is [`ApptainerSandbox`]. The trait is the seam
/// a reward verifier depends on, so the reward path can be exercised in tests with
/// a fake runner that needs no container runtime.
pub trait Sandbox {
    /// Run `spec` to completion, or until its wall-clock budget elapses.
    ///
    /// # Errors
    ///
    /// Returns [`SandboxError`] only if the run could not be carried out — never
    /// for a non-zero exit, a timeout, or a resource kill, which are reported as
    /// [`RunOutcome`]s.
    fn run(&self, spec: &RunSpec) -> Result<RunOutcome, SandboxError>;
}

/// Runs untrusted code under [Apptainer](https://apptainer.org/).
///
/// Construct with [`Default`] (the `apptainer` on `PATH`, a `/bin/bash` in-image
/// shell) or [`ApptainerSandbox::with_bin`] for an explicit path.
#[derive(Debug, Clone)]
pub struct ApptainerSandbox {
    /// The `apptainer` executable — a name on `PATH` or an absolute path.
    bin: PathBuf,
    /// In-image shell used to apply `ulimit`s before `exec`-ing the command.
    shell: PathBuf,
}

impl Default for ApptainerSandbox {
    fn default() -> Self {
        Self {
            bin: PathBuf::from("apptainer"),
            shell: PathBuf::from("/bin/bash"),
        }
    }
}

impl ApptainerSandbox {
    /// Construct with an explicit `apptainer` path (otherwise [`Default`]).
    #[must_use]
    pub fn with_bin(bin: impl Into<PathBuf>) -> Self {
        Self {
            bin: bin.into(),
            ..Self::default()
        }
    }

    /// Build the full `apptainer exec` argument vector for `spec`.
    ///
    /// Pure, so the isolation policy it encodes is unit-testable without running
    /// anything — the `argv_*` tests assert every isolation flag is present.
    #[must_use]
    pub fn build_argv(&self, spec: &RunSpec) -> Vec<String> {
        let mut argv: Vec<String> = vec!["exec".into()];
        // Strong isolation: private PID/IPC/env namespaces + a minimal, read-only
        // rootfs, and crucially no host `$HOME` — so credentials and keys cannot
        // be read. These three are unconditional.
        argv.push("--containall".into());
        argv.push("--no-home".into());
        argv.push("--cleanenv".into());
        if spec.gpu {
            argv.push("--nv".into());
        }
        if matches!(spec.network, NetworkPolicy::None) {
            argv.push("--net".into());
            argv.push("--network".into());
            argv.push("none".into());
        }
        argv.push("--pwd".into());
        argv.push(spec.workdir.display().to_string());
        for bind in &spec.binds {
            argv.push("--bind".into());
            argv.push(bind.render());
        }
        for (key, value) in &spec.env {
            argv.push("--env".into());
            argv.push(format!("{key}={value}"));
        }
        argv.push(spec.image.display().to_string());
        // Inside the image: apply the ulimits, then exec the command directly. The
        // wall-clock budget is owned by the host-side supervisor (outside the
        // container, so the payload cannot evade it) — no in-image timeout.
        argv.push(self.shell.display().to_string());
        argv.push("-c".into());
        argv.push(in_container_script(spec));
        argv
    }
}

impl Sandbox for ApptainerSandbox {
    fn run(&self, spec: &RunSpec) -> Result<RunOutcome, SandboxError> {
        let mut command = Command::new(&self.bin);
        command.args(self.build_argv(spec));
        supervise(command, spec.limits.wall)
    }
}

/// The `bash -c` script run *inside* the image: apply the requested `ulimit`s, then
/// `exec` the command. Each `ulimit` is `|| true` so a shell lacking one option does
/// not abort an otherwise-benign run; the malicious-probe gate verifies the caps that
/// matter are actually enforced. The wall-clock budget is **not** enforced here — the
/// host-side supervisor owns it, so an in-container process cannot evade it.
fn in_container_script(spec: &RunSpec) -> String {
    let limits = &spec.limits;
    let mut script = String::new();
    if let Some(cpu) = limits.cpu {
        script.push_str(&format!("ulimit -t {} || true; ", cpu.as_secs().max(1)));
    }
    if let Some(bytes) = limits.address_space {
        script.push_str(&format!("ulimit -v {} || true; ", bytes / 1024));
    }
    if let Some(procs) = limits.max_procs {
        script.push_str(&format!("ulimit -u {procs} || true; "));
    }
    if let Some(bytes) = limits.max_file {
        script.push_str(&format!("ulimit -f {} || true; ", bytes / 1024));
    }
    let quoted: Vec<String> = spec.command.iter().map(|word| shell_quote(word)).collect();
    script.push_str(&format!("exec {}", quoted.join(" ")));
    script
}

/// POSIX single-quote `word` so it is one literal shell word (a literal single
/// quote becomes `'\''`). The command is ferrl-controlled, but quoting keeps paths
/// with spaces correct and forecloses any accidental word-splitting.
fn shell_quote(word: &str) -> String {
    let escaped = word.replace('\'', r"'\''");
    format!("'{escaped}'")
}

/// Poll cadence for the supervisor's wait loop.
const POLL_INTERVAL: Duration = Duration::from_millis(50);

/// After the child is reaped, the longest the supervisor waits for an output drain
/// to finish. A clean exit closes the pipe and the drain arrives at once; this only
/// bounds the *abnormal* case where a killed process left a descendant holding the
/// pipe open, so the supervisor returns promptly instead of blocking on it.
const DRAIN_GRACE: Duration = Duration::from_secs(2);

/// Largest captured stream kept per pipe (8 MiB). Untrusted output is otherwise
/// unbounded — a payload spewing to stdout could exhaust host memory well within the
/// wall budget — so each drain stops reading here and drops the pipe, leaving the
/// writer to block on a full pipe (then be reaped by the wall-clock supervisor). The
/// eval's machine-read *result* travels via a bound output file, not this log stream.
const CAPTURE_CAP: usize = 8 << 20;

/// Spawn `command`, drain its stdout/stderr concurrently, and enforce `deadline`
/// (wall-clock) by killing the process if it overruns. The concurrent drain avoids
/// the classic pipe-buffer deadlock; the kill is the final authority over a runaway.
fn supervise(mut command: Command, deadline: Duration) -> Result<RunOutcome, SandboxError> {
    command
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    let start = Instant::now();
    let mut child = command.spawn().map_err(SandboxError::Spawn)?;
    let out = drain(child.stdout.take());
    let err = drain(child.stderr.take());

    let mut timed_out = false;
    let status = loop {
        if let Some(status) = child.try_wait().map_err(SandboxError::Supervise)? {
            break status;
        }
        if start.elapsed() >= deadline {
            let _ = child.kill();
            timed_out = true;
            break child.wait().map_err(SandboxError::Supervise)?;
        }
        thread::sleep(POLL_INTERVAL);
    };

    Ok(RunOutcome {
        status: classify_exit(status, timed_out),
        stdout: collect_output(&out),
        stderr: collect_output(&err),
        wall: start.elapsed(),
    })
}

/// Read a child pipe on a detached thread, capturing at most [`CAPTURE_CAP`] bytes
/// and sending them back over a channel (a missing pipe yields an immediately-ready
/// empty result). Stopping at the cap drops the read end, so a payload spewing past
/// it blocks on a full pipe and is reaped by the wall-clock supervisor rather than
/// ballooning host memory. The thread is **not** joined: on a clean exit it finishes
/// at EOF; [`collect_output`] takes the bytes with a timeout, so a descendant holding
/// the write end can never block the supervisor.
fn drain<R: Read + Send + 'static>(pipe: Option<R>) -> Receiver<Vec<u8>> {
    let (tx, rx) = mpsc::channel();
    match pipe {
        Some(mut reader) => {
            thread::spawn(move || {
                let mut buf = Vec::new();
                let mut chunk = [0u8; 8192];
                while buf.len() < CAPTURE_CAP {
                    match reader.read(&mut chunk) {
                        Ok(0) => break,
                        Ok(n) => {
                            let room = CAPTURE_CAP - buf.len();
                            buf.extend_from_slice(&chunk[..n.min(room)]);
                        }
                        Err(ref e) if e.kind() == std::io::ErrorKind::Interrupted => {}
                        Err(_) => break,
                    }
                }
                let _ = tx.send(buf);
            });
        }
        None => {
            let _ = tx.send(Vec::new());
        }
    }
    rx
}

/// Take a drain's bytes — UTF-8-**lossily**, since untrusted output may be binary —
/// waiting at most [`DRAIN_GRACE`] so a descendant holding the pipe cannot block the
/// supervisor. A clean exit closes the pipe and the bytes arrive at once.
fn collect_output(rx: &Receiver<Vec<u8>>) -> String {
    let bytes = rx.recv_timeout(DRAIN_GRACE).unwrap_or_default();
    String::from_utf8_lossy(&bytes).into_owned()
}

/// Classify a finished child into a [`RunStatus`].
fn classify_exit(status: ExitStatus, timed_out: bool) -> RunStatus {
    if timed_out {
        return RunStatus::TimedOut;
    }
    match status.code() {
        Some(code) => RunStatus::Exited(code),
        None => RunStatus::Signaled(signal_of(&status)),
    }
}

/// The terminating signal of a child that exited by signal (`-1` if unknown).
#[cfg(unix)]
fn signal_of(status: &ExitStatus) -> i32 {
    use std::os::unix::process::ExitStatusExt;
    status.signal().unwrap_or(-1)
}

/// Non-Unix fallback: signal numbers are not available.
#[cfg(not(unix))]
fn signal_of(_status: &ExitStatus) -> i32 {
    -1
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec() -> RunSpec {
        RunSpec::new("/img.sif", vec!["python".into(), "/work/eval.py".into()])
    }

    /// Position of `needle` in `argv`, or `None` — keeps the assertions
    /// unambiguous about `String`/`&str` comparison.
    fn pos(argv: &[String], needle: &str) -> Option<usize> {
        argv.iter().position(|s| s.as_str() == needle)
    }

    #[test]
    fn argv_always_isolates_env_home_and_namespaces() {
        let argv = ApptainerSandbox::default().build_argv(&spec());
        for flag in ["exec", "--containall", "--no-home", "--cleanenv"] {
            assert!(pos(&argv, flag).is_some(), "argv missing {flag}");
        }
    }

    #[test]
    fn argv_denies_network_by_default() {
        let argv = ApptainerSandbox::default().build_argv(&spec());
        assert!(
            argv.windows(3)
                .any(|w| w[0] == "--net" && w[1] == "--network" && w[2] == "none"),
            "default spec must deny the network"
        );
    }

    #[test]
    fn argv_shares_host_network_only_on_opt_in() {
        let argv = ApptainerSandbox::default().build_argv(&RunSpec {
            network: NetworkPolicy::Host,
            ..spec()
        });
        assert!(pos(&argv, "--network").is_none());
        assert!(pos(&argv, "--net").is_none());
    }

    #[test]
    fn argv_exposes_gpu_only_when_requested() {
        let off = ApptainerSandbox::default().build_argv(&spec());
        assert!(pos(&off, "--nv").is_none());
        let on = ApptainerSandbox::default().build_argv(&spec().with_gpu(true));
        assert!(pos(&on, "--nv").is_some());
    }

    #[test]
    fn argv_renders_binds_with_their_modes() {
        let argv = ApptainerSandbox::default().build_argv(&spec().with_binds(vec![
            Bind::ro("/h/ref", "/ref"),
            Bind::rw("/h/scratch", "/work"),
        ]));
        assert!(pos(&argv, "/h/ref:/ref:ro").is_some());
        assert!(pos(&argv, "/h/scratch:/work:rw").is_some());
    }

    #[test]
    fn argv_sets_workdir_and_env_allowlist() {
        let argv = ApptainerSandbox::default().build_argv(
            &spec()
                .with_workdir("/work")
                .with_env(vec![("PYTHONHASHSEED".into(), "0".into())]),
        );
        let pwd = pos(&argv, "--pwd").expect("--pwd present");
        assert_eq!(argv[pwd + 1], "/work");
        let env = pos(&argv, "--env").expect("--env present");
        assert_eq!(argv[env + 1], "PYTHONHASHSEED=0");
    }

    #[test]
    fn argv_ends_with_image_then_shell_command() {
        let sandbox = ApptainerSandbox::default();
        let argv = sandbox.build_argv(&spec());
        // ... <image> /bin/bash -c <script>
        let n = argv.len();
        assert_eq!(argv[n - 4], "/img.sif");
        assert_eq!(argv[n - 3], "/bin/bash");
        assert_eq!(argv[n - 2], "-c");
        assert!(argv[n - 1].contains("exec 'python'"));
    }

    #[test]
    fn in_container_script_encodes_the_ulimits_then_execs() {
        let script = in_container_script(&spec().with_limits(ResourceLimits {
            wall: Duration::from_secs(30),
            cpu: Some(Duration::from_secs(25)),
            address_space: Some(2 << 30),
            max_procs: Some(64),
            max_file: Some(8 << 20),
        }));
        assert!(script.contains("ulimit -t 25"));
        assert!(script.contains("ulimit -v 2097152")); // 2 GiB / 1 KiB
        assert!(script.contains("ulimit -u 64"));
        assert!(script.contains("ulimit -f 8192")); // 8 MiB / 1 KiB
                                                    // No in-image timeout: the host supervisor owns the wall-clock budget.
        assert!(!script.contains("timeout"));
        assert!(script.contains("exec 'python' '/work/eval.py'"));
    }

    #[test]
    fn in_container_script_omits_unset_limits() {
        let script = in_container_script(&spec().with_limits(ResourceLimits {
            wall: Duration::from_secs(5),
            cpu: None,
            address_space: None,
            max_procs: None,
            max_file: None,
        }));
        assert!(!script.contains("ulimit"));
        assert_eq!(script, "exec 'python' '/work/eval.py'");
    }

    #[test]
    fn shell_quote_neutralizes_single_quotes() {
        assert_eq!(shell_quote("a b"), "'a b'");
        assert_eq!(shell_quote("it's"), r"'it'\''s'");
    }

    #[test]
    fn command_words_are_shell_quoted_in_the_script() {
        let script = in_container_script(&RunSpec::new(
            "/img.sif",
            vec!["python".into(), "/work/a b.py".into()],
        ));
        assert!(script.contains("'python' '/work/a b.py'"));
    }

    #[test]
    fn run_status_is_success_only_on_zero_exit() {
        assert!(RunStatus::Exited(0).is_success());
        assert!(!RunStatus::Exited(1).is_success());
        assert!(!RunStatus::TimedOut.is_success());
        assert!(!RunStatus::Signaled(9).is_success());
    }

    // --- Host-side supervisor: real subprocess, no container runtime needed. ---

    #[cfg(unix)]
    fn sh(script: &str) -> Command {
        let mut command = Command::new("/bin/sh");
        command.arg("-c").arg(script);
        command
    }

    #[cfg(unix)]
    #[test]
    fn supervise_captures_stdout_on_clean_exit() {
        let outcome = supervise(sh("printf hello"), Duration::from_secs(5)).unwrap();
        assert_eq!(outcome.status, RunStatus::Exited(0));
        assert_eq!(outcome.stdout, "hello");
    }

    #[cfg(unix)]
    #[test]
    fn supervise_captures_stderr_and_nonzero_exit() {
        let outcome = supervise(sh("printf oops 1>&2; exit 3"), Duration::from_secs(5)).unwrap();
        assert_eq!(outcome.status, RunStatus::Exited(3));
        assert_eq!(outcome.stderr, "oops");
    }

    #[cfg(unix)]
    #[test]
    fn supervise_kills_on_wallclock_overrun() {
        // `sh -c 'sleep 30'` exec-replaces sh with sleep, so the kill closes the
        // pipe and the drain returns promptly.
        let outcome = supervise(sh("sleep 30"), Duration::from_millis(300)).unwrap();
        assert_eq!(outcome.status, RunStatus::TimedOut);
        assert!(
            outcome.wall < Duration::from_secs(5),
            "the overrun should have been killed promptly, took {:?}",
            outcome.wall
        );
    }

    #[cfg(unix)]
    #[test]
    fn supervise_reports_a_spawn_failure() {
        let err = supervise(
            Command::new("/no/such/ferrl-binary-xyz"),
            Duration::from_secs(1),
        )
        .unwrap_err();
        assert!(matches!(err, SandboxError::Spawn(_)));
    }

    #[cfg(unix)]
    #[test]
    fn supervise_reports_a_signal_death() {
        // The child kills itself with SIGKILL — it dies by signal (no exit code),
        // so the outcome is `Signaled`, exercising the signal-classification path.
        let outcome = supervise(sh("kill -KILL $$"), Duration::from_secs(5)).unwrap();
        assert!(
            matches!(outcome.status, RunStatus::Signaled(_)),
            "expected a signal death, got {:?}",
            outcome.status
        );
    }

    #[cfg(unix)]
    #[test]
    fn run_supervises_the_built_command() {
        // Point the sandbox at `/bin/true` instead of `apptainer`: `run` still
        // builds the full argv and supervises the process, so the host-side path
        // (`Sandbox::run`) is covered without a container runtime. `/bin/true`
        // ignores the argv and exits 0.
        let outcome = ApptainerSandbox::with_bin("/bin/true")
            .run(&spec())
            .unwrap();
        assert_eq!(outcome.status, RunStatus::Exited(0));
    }

    #[cfg(unix)]
    #[test]
    fn supervise_bounds_captured_output() {
        // A process spewing far more than the cap is captured only up to CAPTURE_CAP,
        // so untrusted output cannot exhaust host memory; past the cap the read end is
        // dropped and the writer EPIPEs, so the run ends without ballooning the buffer.
        let outcome = supervise(sh("head -c 50000000 /dev/zero"), Duration::from_secs(5)).unwrap();
        assert!(
            outcome.stdout.len() <= CAPTURE_CAP,
            "captured {} bytes, cap is {CAPTURE_CAP}",
            outcome.stdout.len()
        );
    }

    #[test]
    fn drain_of_a_missing_pipe_yields_empty_output() {
        // The `None` arm (a child without a captured pipe) sends an immediately
        // ready empty result, so `collect_output` returns "" without waiting.
        let rx = drain(None::<std::io::Empty>);
        assert_eq!(collect_output(&rx), "");
    }
}
